import type {AreaAssessmentContext, EvidenceRecord, ScenarioContext} from './product-contracts';
import {assessPriorities, PRIORITY, PRIORITY_METHOD} from './receptivity/priority';
import type {Snapshot, Weather} from './receptivity/types';

export type CapturedForecast = {weather: Weather[]; source: string; issuedAt: string; detail: string; retrievedAt?: string};

const finite = (value: number | undefined | null) => typeof value === 'number' && Number.isFinite(value) ? value : null;
const iso = (value?: string | null) => value && Number.isFinite(Date.parse(value)) ? new Date(value).toISOString() : null;
const aged = (value: string | null, hours: number, now: number) => !value || now - Date.parse(value) > hours * 3600000 || Date.parse(value) > now;

/** Capture one prepared assessment. This is a copy, never a new environmental calculation. */
export function buildPreventContext(snapshot: Snapshot, cellId: string, horizon: number, now = Date.now(), originalForecast?: CapturedForecast): ScenarioContext {
  const cell = snapshot.cells.find(item => item.id === cellId), index = snapshot.horizons.indexOf(horizon);
  if (!cell || index < 0) throw new Error('Choose a mapped cell and an available environment horizon.');
  const station = snapshot.stations.find(item => item.station.id === cell.stationId);
  const frame = station?.frames.find(item => item.horizon === horizon);
  if (!frame) throw new Error('This area has no weather assessment at the selected horizon. Choose an available horizon.');
  const capturedAt = new Date(now).toISOString();
  const validAt = iso(frame.timestamp);
  if (!validAt) throw new Error('The selected assessment has no valid observation time.');
  const priority = assessPriorities(snapshot, index, now).byCell.get(cellId)!;
  const points = cell.ring, xs = points.map(p => p[0]), ys = points.map(p => p[1]);
  const extent: [number, number, number, number] = [Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)];
  const base = {extent, crs: 'EPSG:4326', resolutionM: null, observedAt: null, validAt: null, retrievedAt: null, coverage: 'unknown' as const};
  const weatherSource = snapshot.sources.find(s => s.id === (horizon ? 'forecast' : 'xema'));
  const weatherTime = iso(station?.frames.find(f => f.horizon === 0)?.timestamp);
  const heat = snapshot.heatwaves?.find(item => item.id === cell.evidence?.heatwaveId);
  const evidence: EvidenceRecord[] = [
    {...base, id: 'weather', source: frame.conditions.source, url: weatherSource?.url, kind: horizon ? 'forecast' : 'observed', observedAt: horizon ? null : validAt, validAt, retrievedAt: iso(weatherSource?.retrievedAt), units: '°C; % RH; km/h at 10 m; degrees from north; mm per interval', status: priority.weatherFresh ? 'available' : 'stale', coverage: 'partial', consumers: ['Prevent fine-fuel moisture and spread index', 'Sage captured weather forcing'], detail: `${station?.station.name}; ${cell.stationDistanceKm.toFixed(1)} km from cell. Station-scale input, not a measurement at each cell. Rain interval ${frame.conditions.stepHours} h ends at valid time.`},
    {...base, id: 'fine-fuel-moisture', source: `GINGER ${snapshot.version} / FFMC`, kind: 'derived', validAt, retrievedAt: snapshot.generatedAt, units: '% dry mass', status: priority.weatherFresh ? 'available' : 'stale', coverage: 'partial', consumers: ['Prevent review rules', 'Sage initial dead fine-fuel moisture'], detail: 'Derived dead litter moisture after station-history spin-up; not a measured live-fuel or soil-moisture value.'},
    {...base, id: 'fuel-geography', source: cell.fuel.source, kind: 'derived', resolutionM: snapshot.cellSizeM, units: 'land-cover class; area fraction; neighbourhood continuity', status: 'available', coverage: 'partial', consumers: ['Prevent review rules', 'Sage landscape context'], detail: `Epoch ${cell.fuel.epoch}; ${cell.fuel.type}; ${(cell.fuel.burnableFraction * 100).toFixed(0)}% cover. Sage independently samples its supported fuel landscape; this cell is context, not per-tree fuel loads.`},
    {...base, id: 'terrain', source: snapshot.sources.find(s => /terrain|elevation|dem|slope/i.test(s.name))?.name || 'Prepared geographic terrain', kind: 'derived', resolutionM: snapshot.cellSizeM, units: 'm elevation; degrees slope/aspect', status: finite(cell.terrain.slope) === null ? 'unavailable' : 'available', coverage: 'partial', consumers: ['Prevent review rules', 'Sage location context'], detail: 'Prepared-cell slope supports review. Sage retrieves terrain at its own model resolution.'},
    {...base, id: 'vegetation-indices', source: 'Sentinel-2 clear-pixel vegetation indices', kind: 'derived', observedAt: iso(cell.fuel.satelliteAt), validAt: iso(cell.fuel.satelliteAt), resolutionM: snapshot.cellSizeM, units: 'unitless NDVI / NDMI', coverage: (cell.fuel.satelliteCoverage ?? 0) >= .5 ? 'partial' : 'unknown', status: finite(cell.fuel.ndmi) === null ? 'unavailable' : aged(iso(cell.fuel.satelliteAt), 240, now) ? 'stale' : 'available', consumers: ['Prevent vegetation review rule'], detail: `NDVI ${finite(cell.fuel.ndvi) ?? 'unknown'}, NDMI ${finite(cell.fuel.ndmi) ?? 'unknown'}; coverage ${cell.fuel.satelliteCoverage === undefined ? 'unknown' : `${Math.round(cell.fuel.satelliteCoverage * 100)}%`}. Spectral indicators do not replace physical fuel moisture.`},
    {...base, id: 'thermal', source: snapshot.satellite?.source || 'Thermal observations', kind: 'observed', observedAt: iso(priority.thermal?.latestAt), validAt: iso(priority.thermal?.latestAt), retrievedAt: iso(snapshot.satellite?.retrievedAt), units: 'thermal anomaly; acquisition time', status: snapshot.satellite?.status === 'live' && !aged(iso(snapshot.satellite.retrievedAt), .5, now) ? 'available' : 'stale', consumers: ['Prevent verification priority'], detail: priority.thermal ? `${priority.thermal.confidence} confidence; ${priority.thermal.periods} trusted observation periods. Unverified thermal signal, not a confirmed incident.` : 'No selected local thermal signal. Absence does not rule out fire.'},
    {...base, id: 'infrastructure', source: 'Prepared Catalonia mapped asset inventory', kind: 'derived', observedAt: iso(cell.localExposure?.sourceDate), validAt: iso(cell.localExposure?.sourceDate), units: 'deduplicated mapped asset identities', status: !cell.localExposure ? 'unavailable' : aged(iso(cell.localExposure.sourceDate), 720, now) ? 'stale' : 'available', coverage: cell.localExposure?.status === 'ready' ? 'full' : 'partial', consumers: ['Prevent consequence review priority', 'Sage geometric exposure inventory'], detail: `Within ${cell.localExposure?.rangeM ?? 'unknown'} m. Mapped facilities and road features are not verified occupancy, population or official closures.`},
    {...base, id: 'soil-moisture', source: frame.conditions.source, kind: horizon ? 'forecast' : 'observed', validAt, retrievedAt: iso(weatherSource?.retrievedAt), units: 'm³/m³ model soil layer', status: finite(frame.conditions.soilMoisture) === null ? 'unavailable' : 'available', consumers: ['Inspection only'], detail: `Soil moisture ${finite(frame.conditions.soilMoisture) ?? 'unavailable'}. Not used as fuel moisture or as a spread-model input.`},
  ];
  evidence.push({...base, id: 'heatwave-screening', source: heat?.source || 'Heatwave screening', kind: 'derived', validAt, retrievedAt: iso(heat?.retrievedAt), units: 'daily maximum °C; local calendar days', coverage: 'partial', status: !heat || heat.status === 'unavailable' ? 'unavailable' : aged(iso(heat.retrievedAt), 2, now) ? 'stale' : 'available', consumers: ['Prevent combined review rules'], detail: heat ? `${heat.status}; municipality threshold ${heat.thresholdC ?? 'unknown'}°C. Episodes: ${heat.episodes.map(episode=>`${episode.start} to ${episode.end}, ${episode.days} days, peak ${episode.peakC}°C`).join('; ') || 'none established'}. ${heat.detail || ''} Modelled screening, not an official warning or a fuel-moisture measurement.` : 'No matched heatwave evidence for this cell.'});
  const limitations = [...priority.missing.map(v => `Missing or stale: ${v}.`), 'Experimental review rules; no ignition probability or exact ignition prediction.', `Weather support is ${cell.stationDistanceKm.toFixed(1)} km from the selected cell.`, 'Live-fuel moisture and canopy fuel loads are unmeasured.'];
  if (aged(weatherTime, 1.5, now)) limitations.unshift(`Historical weather basis: ${weatherTime || 'unknown'}. This scenario is not a current-conditions forecast.`);
  const forecastMatches = originalForecast && originalForecast.issuedAt === station!.forecastIssuedAt && originalForecast.source === station!.forecastSource;
  const instant = Date.parse(validAt);
  const capturedWeather: Weather[] = [frame.conditions, ...(forecastMatches ? originalForecast.weather.filter(w => Date.parse(w.time) + w.stepHours * 3600000 > instant && Date.parse(w.time) <= instant + 24 * 3600000) : station!.frames.filter(f => f.horizon > horizon).map(f => f.conditions))];
  const supportedWeather = capturedWeather.filter(w => finite(w.windDirection) !== null && [w.temperature,w.relativeHumidity,w.windSpeed,w.precipitation,w.stepHours].every(Number.isFinite) && w.stepHours > 0);
  if (finite(frame.conditions.windDirection) === null) limitations.push('Wind direction is missing in the selected environmental frame. Only a captured, timestamp-matched forecast can replace that interval; otherwise Sage cannot run.');
  limitations.push(forecastMatches ? 'Hourly model weather is held between its valid samples. Precipitation retains its ending-interval accumulation and is not a resolved rain field.' : 'The original hourly forecast cache is unavailable or has a different issue time. Sparse assessment samples may leave unsupported weather gaps.');
  limitations.push('Solar radiation components are unavailable in this assessment; solar-driven drying is not supported by these captured inputs.');
  if (forecastMatches) evidence.push({...base, id: 'captured-hourly-forecast', source: originalForecast.source, kind: 'forecast', validAt, retrievedAt: originalForecast.retrievedAt || null, units: '°C; % RH; km/h; degrees from north; mm per interval', coverage: 'partial', status: aged(iso(originalForecast.issuedAt), 6, now) ? 'stale' : 'available', consumers: ['Sage captured weather forcing'], detail: `Captured original hourly forecast matching prepared assessment issue ${originalForecast.issuedAt}. ${originalForecast.detail}`});
  const assessment: AreaAssessmentContext = {id: `${PRIORITY_METHOD}:${snapshot.generatedAt}:${cellId}:${horizon}`, cellId, name: cell.name, center: [...cell.center], geometry: {type: 'Polygon', coordinates: [cell.ring.map(p => [...p])]}, capturedAt, validAt, horizonHours: horizon, conclusion: PRIORITY[priority.level].label, drivers: priority.reasons.slice(0, 3), limitations, nextAction: priority.action, evidence};
  return structuredClone({version: 1, id: '', name: `${cell.name} · hypothetical ignition`, createdAt: capturedAt, basis: 'hypothetical', center: [...cell.center], ignitionAt: validAt, assessment, incident: null, evidence,
    inputs: {weather: supportedWeather.map(w => ({time: w.time, temperatureC: w.temperature, humidityPct: w.relativeHumidity, windKmh: w.windSpeed, windFromDegrees: w.windDirection!, precipitationMm: w.precipitation, directNormalWm2: null, diffuseWm2: null, validForMinutes: w.stepHours * 60, source: w.source})), deadMoisturePct: finite(frame.fineFuelMoisture), liveMoisturePct: null, fuel: {type: cell.fuel.type, source: cell.fuel.source, epoch: cell.fuel.epoch, continuity: finite(cell.fuel.continuity)}, terrain: {elevationM: finite(cell.terrain.elevation), slopeDegrees: finite(cell.terrain.slope), aspectDegrees: finite(cell.terrain.aspect)}},
    assumptions: ['Hypothetical ignition at the selected environmental valid time, not a prediction that ignition will occur.', 'Initial dead fine-fuel moisture comes from the FFMC litter estimate.', 'Live-fuel moisture, ignition radius, wind adjustment and structural transfer remain explicit Sage run assumptions.'], limitations} satisfies ScenarioContext);
}

export function buildDirectScenario(input: {lat: number; lon: number; name?: string; ignitionAt?: string}, now = Date.now()): ScenarioContext {
  if (![input.lat, input.lon].every(Number.isFinite) || input.lat < 40 || input.lat > 43 || input.lon < 0 || input.lon > 4) throw new Error('Choose a location in the supported Catalonia domain.');
  const createdAt = new Date(now).toISOString(), ignitionAt = input.ignitionAt ? iso(input.ignitionAt) : createdAt;
  if (!ignitionAt) throw new Error('Provide a valid hypothetical ignition time.');
  return {version: 1, id: '', name: String(input.name || 'Hypothetical scenario').slice(0, 100), createdAt, basis: 'hypothetical', center: [input.lon, input.lat], ignitionAt, assessment: null, incident: null, evidence: [], inputs: {weather: [], deadMoisturePct: null, liveMoisturePct: null}, assumptions: ['Operator-selected hypothetical ignition; no confirmed wildfire is asserted.', 'Weather and landscape are retrieved by Sage when the scenario is run.'], limitations: ['No Prevent assessment is attached. Inspect the run input sources and assumptions before interpretation.']};
}
