'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import type {RunState} from '@/lib/sage/types';
import type {ScenarioContext} from '@/lib/product-contracts';
import ReturnedForecast from './returned-forecast';
import dynamic from 'next/dynamic';
import {ArrowUpRight,ChevronRight,Database,Layers3,Pause,Play,RefreshCw,X} from 'lucide-react';
import {reviewZones} from '@/lib/receptivity/zones';
import {assessPriorities,PRIORITY} from '@/lib/receptivity/priority';
import {HORIZONS,type Snapshot} from '@/lib/receptivity/types';
import {exposureCategories,type ExposureCategory,type ExposureSummary} from '@/lib/exposure/types';
import type {Metric} from './map';
import EnvironmentEvidence from './environment-evidence';
import ExposureSummaryView from '../exposure-summary';
import Modal from '../modal';
import './workspace.css';
const Map=dynamic(()=>import('./map'),{ssr:false});
const stamp=(value?:string|null)=>value?new Date(value).toLocaleString('en-GB',{timeZone:'Europe/Madrid',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})+' · Madrid':'Unknown';
const fmt=(value?:number|null,unit='')=>typeof value==='number'&&Number.isFinite(value)?`${Number(value.toFixed(1))}${unit}`:'Unavailable';
const metricNames:Record<Metric,string>={priority:'Review priority',receptivity:'Regional fuel dryness',spread:'Weather spread index',moisture:'Fine-fuel moisture',vegetation:'Vegetation',evidence:'Satellite & heat review'};
export default function ReceptivityWorkspace(){
 const router=useRouter(),search=useSearchParams();
 const runId=search.get('sageRun'),scenarioId=search.get('scenario');
 const [returnedRun,setReturnedRun]=useState<RunState|null>(null),[contextError,setContextError]=useState('');
 const [data,setData]=useState<Snapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[stale,setStale]=useState(false),[index,setIndex]=useState(0),[selectedId,setSelectedId]=useState<string|null>(null),[focusKey,setFocusKey]=useState(0),[metric,setMetric]=useState<Metric>('priority'),[showStations,setShowStations]=useState(false),[showWind,setShowWind]=useState(false),[showOfficial,setShowOfficial]=useState(false),[drawer,setDrawer]=useState<'areas'|'selection'|null>(null),[layers,setLayers]=useState(false),[sources,setSources]=useState(false),[playing,setPlaying]=useState(false),[now,setNow]=useState(Date.now()),[creating,setCreating]=useState(false),[scenarioError,setScenarioError]=useState('');
 const [exposureLayers,setExposureLayers]=useState<ExposureCategory[]>([]),[exposureStatus,setExposureStatus]=useState('Inventory loading…'),[exposure,setExposure]=useState<ExposureSummary>(),[exposureError,setExposureError]=useState('');
 const [zoneSearch,setZoneSearch]=useState('');
 const etag=useRef(''),pending=useRef(false);
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){setDrawer(null);setLayers(false);setPlaying(false);}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
 const refresh=useCallback(async()=>{if(pending.current)return;pending.current=true;setLoading(true);try{const response=await fetch('/api/receptivity',{headers:etag.current?{'If-None-Match':etag.current}:{},signal:AbortSignal.timeout(30000)});if(response.status===304){setError('');return;}if(!response.ok)throw Error(`Environmental pipeline returned ${response.status}`);const result=await response.json();if(result.snapshot){setData(result.snapshot);setNow(Date.now());etag.current=response.headers.get('etag')||'';}setStale(!!result.stale);setError(result.error||'');}catch(e){setError(e instanceof Error?e.message:'Environmental evidence unavailable');}finally{pending.current=false;setLoading(false);}},[]);
 useEffect(()=>{void refresh();const poll=setInterval(()=>void refresh(),15000),clock=setInterval(()=>setNow(Date.now()),30000);return()=>{clearInterval(poll);clearInterval(clock);};},[refresh]);
 useEffect(()=>{
  const controller=new AbortController();setReturnedRun(null);setContextError('');
  if(!scenarioId&&!runId){const cell=search.get('cell');if(cell){setSelectedId(cell);const restored=HORIZONS.findIndex(h=>h===Number(search.get('horizon')||0));if(restored>=0)setIndex(restored);setDrawer('selection');setFocusKey(key=>key+1);}else setDrawer('areas');return;}
  void (async()=>{
   let context:ScenarioContext|undefined;
   if(runId){const response=await fetch(`/api/sage/runs/${encodeURIComponent(runId)}`,{signal:controller.signal});if(!response.ok)throw Error('Saved forecast unavailable. You can still inspect current Prevent evidence.');const saved=await response.json() as RunState;if(controller.signal.aborted)return;setReturnedRun(saved);context=saved.result?.scenario;}
   if(!context&&scenarioId){const response=await fetch(`/api/scenarios/${encodeURIComponent(scenarioId)}`,{signal:controller.signal});if(!response.ok)throw Error('Saved assessment unavailable. Select a map area to continue.');context=(await response.json()).scenario;}
   const assessment=context?.assessment;if(!assessment||controller.signal.aborted)return;
   setSelectedId(assessment.cellId);const restored=HORIZONS.findIndex(h=>h===assessment.horizonHours);if(restored>=0)setIndex(restored);setDrawer('selection');setFocusKey(key=>key+1);
  })().catch(error=>{if(!controller.signal.aborted)setContextError(error instanceof Error?error.message:'Saved context unavailable.');});
  return()=>controller.abort();
 },[scenarioId,runId,search]);

 const availableTimes=useMemo(()=>HORIZONS.map((h,i)=>data?.stations.some(s=>s.frames.some(f=>f.horizon===h))?i:-1).filter(i=>i>=0),[data]);
 useEffect(()=>{if(!playing||availableTimes.length<2)return;const timer=setInterval(()=>setIndex(i=>availableTimes[(availableTimes.indexOf(i)+1)%availableTimes.length]),2200);return()=>clearInterval(timer);},[playing,availableTimes]);
 const selected=useMemo(()=>data?.cells.find(c=>c.id===selectedId)??null,[data,selectedId]);
 const priorities=useMemo(()=>data?assessPriorities(data,index,now):null,[data,index,now]);
 const zones=useMemo(()=>data&&priorities?reviewZones(data.cells,priorities.byCell):[],[data,priorities]);
 const visibleZones=zones.filter(zone=>zone.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(zoneSearch.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()));
 const priority=selected?priorities?.byCell.get(selected.id):undefined;
 const station=data?.stations.find(s=>s.station.id===selected?.stationId),frame=station?.frames.find(f=>f.horizon===HORIZONS[index]);
 const isStale=stale||!!data?.observationRange&&now-Date.parse(data.observationRange.oldest)>90*60000;
 const partialEvidence=!!error||!!data?.sources.some(source=>source.status==='unavailable'||source.status==='stale');
 const select=(id:string,fly=false)=>{setSelectedId(id);setDrawer('selection');setLayers(false);setScenarioError('');if(fly)setFocusKey(key=>key+1);};
 useEffect(()=>{const controller=new AbortController();setExposure(undefined);setExposureError('');if(!selected)return;void fetch(`/api/exposure/cell?cell=${encodeURIComponent(selected.id)}&horizon=${HORIZONS[index]}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw Error();return response.json();}).then(result=>{if(!controller.signal.aborted)setExposure(result.exposure);}).catch(()=>{if(!controller.signal.aborted)setExposureError('Infrastructure assessment unavailable.');});return()=>controller.abort();},[selected?.id,index,data?.generatedAt]);
 const explore=async()=>{if(!selected||creating)return;setCreating(true);setScenarioError('');try{const response=await fetch('/api/scenarios',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cellId:selected.id,horizon:HORIZONS[index]})});const result=await response.json();if(!response.ok||!result.scenario?.id)throw Error(result.error||'Could not preserve this assessment.');router.push(`/sage?scenario=${encodeURIComponent(result.scenario.id)}`);}catch(e){setScenarioError(e instanceof Error?e.message:'Scenario creation unavailable.');}finally{setCreating(false);}};
 const leading=(priority?.reasons.slice(0,3)||[]).map(reason=>{
  if(reason.startsWith('Available evidence does not meet'))return 'No combined local review rule is met.';
  if(reason.startsWith('Current thermal'))return `Thermal signal ${priority?.thermal?.distanceKm.toFixed(1)} km away; ${priority?.thermal?.confidence} confidence. Verify locally.`;
  if(reason.includes('fine-fuel moisture')&&selected)return `Fine-fuel moisture ${fmt(frame?.fineFuelMoisture,'%')}; ${Math.round(selected.fuel.burnableFraction*100)}% fuel cover, ${Math.round(selected.fuel.continuity*100)}% continuity.`;
  if(reason.startsWith('Dry fuel coincides'))return `Dry fuels with ${fmt(frame?.conditions.windSpeed,' km/h')} wind.`;
  if(reason.startsWith('Mapped slope'))return `Mapped slope ${fmt(selected?.terrain.slope,'°')} warrants terrain inspection.`;
  return reason;
 });
 const nextAction=priority?{verify:'Verify the thermal signal and nearby infrastructure.',review:'Inspect the evidence; consider a field check.',watch:'Watch for changes in weather and thermal evidence.',routine:'Continue monitoring; no trigger does not establish safety.',unknown:'Restore missing inputs before interpreting conditions.'}[priority.level]:'';
 return <main className="r-workspace prevent-workspace">
  <Map priorities={priorities?.byCell} now={now} exposureLayers={exposureLayers} onExposureStatus={setExposureStatus} data={data} index={index} metric={metric} stations={showStations} wind={showWind} official={showOfficial} selected={selected} onSelect={id=>select(id)} focusKey={focusKey}/>
  <section className="prevent-overview" aria-label="Prevent overview"><p className="r-eyebrow">PRE-FIRE INTELLIGENCE</p><h1>Where should we look first?</h1><p>Select a zone. Inspect conditions. Explore a possible fire.</p><button className="prevent-area-toggle" aria-expanded={drawer==='areas'} onClick={()=>{setDrawer(drawer==='areas'?null:'areas');setLayers(false);}}>{zones.length?`Explore ${zones.length} mapped zones`:'Explore mapped zones'}<ChevronRight size={15}/></button></section>
  <div className="prevent-health"><button onClick={()=>setSources(true)} className={isStale||partialEvidence?'degraded':''}><Database size={14}/>{!data?'Preparing evidence':isStale?'Stale evidence':partialEvidence?'Partial evidence':'Evidence ready'}</button><button aria-label="Reload available environmental evidence" title="Reload the latest stored snapshot; data collection runs separately" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={14} className={loading?'spinning':''}/></button></div>
  {contextError&&<p className="prevent-context-error" role="status">{contextError}</p>}
  <div className="r-layer-anchor"><button className="r-layers-toggle" aria-expanded={layers} onClick={()=>{setLayers(!layers);if(!layers)setDrawer(null);}}><Layers3 size={16}/>{metricNames[metric]}</button>{layers&&<section className="r-layer-menu r-panel" aria-label="Prevent layers"><div className="r-panel-title">LAYERS<button aria-label="Close layers" onClick={()=>setLayers(false)}><X size={15}/></button></div><fieldset><legend>Environmental layer</legend>{(Object.keys(metricNames) as Metric[]).map(m=><label key={m}><input type="radio" name="prevent-metric" checked={metric===m} onChange={()=>setMetric(m)}/>{metricNames[m]}</label>)}</fieldset><label><input type="checkbox" checked={showWind} onChange={e=>setShowWind(e.target.checked)}/>Wind</label><label><input type="checkbox" checked={showStations} onChange={e=>setShowStations(e.target.checked)}/>Weather stations</label><label><input type="checkbox" checked={showOfficial} disabled={!data?.official.comparable} onChange={e=>setShowOfficial(e.target.checked)}/>Official Pla Alfa</label><div className="r-panel-title">MAPPED INFRASTRUCTURE</div>{(Object.keys(exposureCategories) as ExposureCategory[]).map(category=><label key={category}><input type="checkbox" checked={exposureLayers.includes(category)} onChange={e=>setExposureLayers(v=>e.target.checked?[...v,category]:v.filter(c=>c!==category))}/><i className="exposure-swatch" style={{background:exposureCategories[category].color}}/>{exposureCategories[category].label}</label>)}<p>{exposureStatus}</p></section>}</div>
  {drawer&&<aside className="prevent-drawer r-panel" aria-label={drawer==='areas'?'Mapped zones':'Selected area assessment'}><div className="r-panel-title"><span>{drawer==='areas'?'BARCELONA REGION · ZONES':'PREVENT ASSESSMENT'}</span><button aria-label="Close assessment" onClick={()=>setDrawer(null)}><X size={17}/></button></div><div className="prevent-drawer-scroll">
   {drawer==='areas'?<>{!data?<div className="r-loading" role="status">{error||'Preparing environmental evidence…'}</div>:<><p className="prevent-list-context">Choose a zone to open its highest-priority mapped cell. Conditions vary within each zone.</p><label className="prevent-zone-search">Find a zone<input type="search" value={zoneSearch} onChange={event=>setZoneSearch(event.target.value)} placeholder="Town or municipality"/></label><ol className="r-priority-list">{visibleZones.slice(0,30).map(zone=><li key={zone.name}><button onClick={()=>select(zone.cell.id,true)}><strong>{zone.name}</strong><span className="r-priority-label" style={{color:PRIORITY[zone.priority.level].color}}>{PRIORITY[zone.priority.level].label}</span><small>{zone.attentionCells?`${zone.attentionCells} cells warrant attention`:`${zone.cells} mapped ${zone.cells===1?'cell':'cells'}`}<ChevronRight size={13}/></small></button></li>)}</ol>{!visibleZones.length&&<p className="prevent-map-hint">No mapped zone matches this search.</p>}{visibleZones.length>30&&<p className="prevent-map-hint">Showing 30 of {visibleZones.length} zones. Search to find another.</p>}<details className="r-evidence"><summary>Assessment basis</summary><p>Priorities combine supported weather, mapped fuels, slope, thermal signals and nearby infrastructure. They are review rules, not ignition predictions.</p><p>{priorities?.counts.unknown.toLocaleString()} cells have incomplete evidence.</p></details></>}</>:!selected?<p className="prevent-list-context" role="status">{loading?'Loading the selected area…':'This saved area is outside the available map inventory. Select another mapped area to inspect current evidence.'}</p>:<>
    <button className="prevent-back-zones" onClick={()=>setDrawer('areas')}>← All zones</button><div className="r-sage-location"><p className="r-eyebrow">{isStale?'STALE · ':''}{index?'FORECAST':'OBSERVED / DERIVED'} · {HORIZONS[index]?`+${HORIZONS[index]}H`:'NOW'}</p><h2>{selected.name}</h2><p>{stamp(frame?.timestamp)}</p></div>
    {priority&&<section className="prevent-conclusion"><h3 style={{color:PRIORITY[priority.level].color}}>{PRIORITY[priority.level].label}</h3><ul>{leading.map(reason=><li key={reason}>{reason}</li>)}</ul><p className="prevent-limitation">{priority.missing.length?`Limited: ${priority.missing.slice(0,2).join('; ')}.`:'Station-scale weather; local fuel loads are unmeasured.'}</p><p className="prevent-next">{nextAction}</p></section>}
    <div className="prevent-sage-action"><button disabled={creating||!frame} onClick={()=>void explore()}>{creating?'Preserving evidence…':'Explore in Sage'}<ArrowUpRight size={16}/></button><small>Hypothetical ignition · retains evidence and time</small>{scenarioError&&<p role="alert">{scenarioError}</p>}</div>
    <div className="prevent-sage-action"><button onClick={()=>router.push(`/satellite?${new URLSearchParams({lat:String(selected.center[1]),lon:String(selected.center[0]),from:'prevent',cell:selected.id,horizon:String(HORIZONS[index])})}`)}>Satellite imagery & vegetation<ArrowUpRight size={16}/></button><small>See the image and analyse vegetation condition</small></div>
    {returnedRun?.result?.scenario?.assessment?.cellId===selected.id&&<ReturnedForecast run={returnedRun} minute={Number(search.get('minute')||0)}/>}
    <details className="r-evidence"><summary>Why this assessment?</summary>{priority?.reasons.map(reason=><p key={reason}>{reason}</p>)}{priority?.missing.map(missing=><p key={missing}>Missing or stale: {missing}.</p>)}<p>Priority is not a calibrated ignition probability. A thermal anomaly is unverified evidence.</p></details>
    <details className="r-evidence"><summary>Weather, fuel & terrain</summary><dl className="prevent-values">{[['Dead fine-fuel moisture',fmt(frame?.fineFuelMoisture,'% dry mass')],['Temperature / RH',`${fmt(frame?.conditions.temperature,'°C')} / ${fmt(frame?.conditions.relativeHumidity,'%')}`],['Wind / gust',`${fmt(frame?.conditions.windSpeed,' km/h')} / ${fmt(frame?.conditions.windGust,' km/h')}`],['Rain · previous 24h / 7d',`${fmt(station?.history.rain24h,' mm')} / ${fmt(station?.history.rain7d,' mm')}`],['Mapped fuel',`${Math.round(selected.fuel.burnableFraction*100)}% · ${selected.fuel.type}`],['Continuity',fmt(selected.fuel.continuity*100,'%')],['Slope / aspect',`${fmt(selected.terrain.slope,'°')} / ${fmt(selected.terrain.aspect,'°')}`],['NDVI / NDMI',`${fmt(selected.fuel.ndvi)} / ${fmt(selected.fuel.ndmi)}`],['Model soil moisture',fmt(frame?.conditions.soilMoisture,' m³/m³')]].map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><p>{station?.station.name||'No station'} · {fmt(selected.stationDistanceKm,' km away')}. Weather is shared across nearby cells.</p><p>Fine-fuel moisture is derived litter moisture. NDMI and soil moisture are distinct evidence, not substitutes.</p></details>
    <details className="r-evidence"><summary>Nearby mapped infrastructure</summary>{exposureError?<p>{exposureError}</p>:<ExposureSummaryView exposure={exposure} context="receptivity" compact/>}<p>Nearby assets are context. Sage calculates forecast intersections.</p></details>
    <details className="r-evidence"><summary>Evidence & assumptions</summary><p>Assessment {data?.version} · captured {stamp(data?.generatedAt)}.</p><p>Weather valid {stamp(frame?.timestamp)}. Forecast source: {station?.forecastSource||'Unavailable'}.</p><p>Land cover {selected.fuel.source} · {selected.fuel.epoch}. Vegetation imagery {stamp(selected.fuel.satelliteAt)}.</p>{station?.quality.map(note=><p key={note}>{note}</p>)}{data&&<EnvironmentEvidence data={data} cell={selected} stale={isStale} priority={priority}/>}<code>{selected.id}</code></details>
   </>}
  </div></aside>}
  <div className="r-map-legend"><span>{metricNames[metric]}</span>{metric==='priority'?<p>{Object.entries(PRIORITY).map(([key,value])=><span key={key}><i style={{background:value.color}}/>{key==='verify'?'Verify':key==='review'?'Review':key==='watch'?'Watch':key==='routine'?'No trigger':'Unknown'}</span>)}</p>:<p>{metric==='vegetation'?'Mapped vegetation cover':metric==='evidence'?'Current evidence · not confirmed fires':metric==='moisture'?'Derived dead fine-fuel moisture':'Relative index · not ignition probability'}</p>}</div>
  <nav className="r-timeline" aria-label="Environment time"><button className="r-play" aria-label={playing?'Pause environment timeline':'Play environment timeline'} disabled={availableTimes.length<2} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><span className="prevent-time-label">Environment</span><div className="r-time-stops">{HORIZONS.map((h,i)=><button key={h} aria-pressed={index===i} disabled={!data||!data.stations.some(s=>s.frames.some(f=>f.horizon===h))} onClick={()=>{setIndex(i);setPlaying(false);}}>{h?`+${h}h`:'Now'}</button>)}</div></nav>
  {sources&&<Modal title="Evidence & data health" subtitle="Prevent · integrated review rules" onClose={()=>setSources(false)} wide><div className="r-source-body">{error&&<p role="status">{error}</p>}<p className="r-source-intro">Weather estimates dead-litter moisture. Fuel, terrain, fresh spectral indicators and mapped infrastructure support review priority. Thermal evidence prompts verification. No ignition probability is calculated.</p><p>Snapshot {stamp(data?.generatedAt)} · observations {stamp(data?.observationRange?.oldest)}.</p>{data?.sources.map(source=><article key={source.id}><div><h3>{source.name}</h3><span data-status={source.status}>{source.status}</span></div><p>{source.detail}</p><small>Valid {stamp(source.validAt)} · retrieved {stamp(source.retrievedAt)}</small><a href={source.url} target="_blank" rel="noreferrer">Source documentation<ArrowUpRight size={12}/></a></article>)}{data?.warnings.map(warning=><p className="r-source-warning" key={warning}>{warning}</p>)}<a href="/methodology">Detailed method</a></div></Modal>}
 </main>;
}
