'use client';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {Activity,ArrowUpRight,ChevronRight,Database,Flame,Layers3,Pause,Play,RefreshCw,Wind,X} from 'lucide-react';
import {HORIZONS,type Snapshot,type CellResult} from '@/lib/receptivity/types';
import {classificationLabel,explainCell} from '@/lib/receptivity/model';
import type {Metric} from './map';
import Modal from '../modal';
import './workspace.css';
const Map=dynamic(()=>import('./map'),{ssr:false});
const color=(v:number|null)=>v===null?'#8a969e':v>=90?'#e56361':v>=80?'#ed974f':v>=65?'#c4ae62':v>=40?'#96a98c':'#79a18f';
const stamp=(s:string|undefined|null)=>s?new Date(s).toLocaleTimeString('en-GB',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit'}):'—';
const fullStamp=(s:string|undefined|null)=>s?new Date(s).toLocaleString('en-GB',{timeZone:'Europe/Madrid',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})+' CEST/CET':'Unknown';
const fmt=(v:number|undefined|null,unit='')=>v===undefined||v===null?'Unavailable':`${Number(v.toFixed(1))}${unit}`;
const ago=(s:string,now:number)=>`${Math.max(0,Math.floor((now-Date.parse(s))/60000))} min ago`;
function spatialRanking(cells:CellResult[],index:number,emerging=false){const sorted=cells.filter(c=>c.receptivity[index]!==null&&(!emerging||c.velocity!==null&&c.velocity>0)).sort((a,b)=>emerging?(b.velocity??0)-(a.velocity??0):b.receptivity[index]!-a.receptivity[index]!||b.fuel.burnableFraction-a.fuel.burnableFraction);const picked:CellResult[]=[];for(const c of sorted){if(picked.every(p=>Math.hypot((c.center[0]-p.center[0])*.75,c.center[1]-p.center[1])>.022))picked.push(c);if(picked.length===7)break;}return picked;}
export default function ReceptivityWorkspace(){
 const [data,setData]=useState<Snapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[stale,setStale]=useState(false),[index,setIndex]=useState(0),[selectedId,setSelectedId]=useState<string|null>(null),[focusKey,setFocusKey]=useState(0),[metric,setMetric]=useState<Metric>('receptivity'),[showStations,setShowStations]=useState(false),[showWind,setShowWind]=useState(false),[showOfficial,setShowOfficial]=useState(false),[layers,setLayers]=useState(false),[sources,setSources]=useState(false),[playing,setPlaying]=useState(false),[ranking,setRanking]=useState<'hotspots'|'emerging'>('hotspots'),[now,setNow]=useState(Date.now()),[mobilePanel,setMobilePanel]=useState<'rank'|'sage'|null>(null);
 const etag=useRef(''),pending=useRef(false),initial=useRef(true);
 const refresh=useCallback(async()=>{if(pending.current)return;pending.current=true;setLoading(true);try{const r=await fetch('/api/receptivity',{headers:etag.current?{'If-None-Match':etag.current}:{},signal:AbortSignal.timeout(30000)});if(r.status===304){setError('');return;}if(!r.ok)throw Error(`Live pipeline returned ${r.status}`);const result=await r.json();if(result.snapshot){const s=result.snapshot as Snapshot;setData(s);etag.current=r.headers.get('etag')||'';if(initial.current){setSelectedId(spatialRanking(s.cells,0)[0]?.id??null);initial.current=false;}}setStale(result.stale);setError(result.error||'');}catch(e){setError(e instanceof Error?e.message:'Live connection unavailable');}finally{pending.current=false;setLoading(false);}},[]);
 useEffect(()=>{void refresh();const id=setInterval(()=>void refresh(),15000),clock=setInterval(()=>setNow(Date.now()),30000);return()=>{clearInterval(id);clearInterval(clock);};},[refresh]);
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setIndex(i=>(i+1)%HORIZONS.length),2200);return()=>clearInterval(id);},[playing]);
 const selected=useMemo(()=>data?.cells.find(c=>c.id===selectedId)??null,[data,selectedId]);
 const station=data?.stations.find(s=>s.station.id===selected?.stationId);const assessment=station?.frames.find(f=>f.horizon===HORIZONS[index]);const score=selected?.receptivity[index]??null;
 const sorted=useMemo(()=>data?spatialRanking(data.cells,index,ranking==='emerging'):[],[data,index,ranking]);
 const isStale=stale||!!data?.observationRange&&now-Date.parse(data.observationRange.oldest)>90*60000;
 const select=(id:string,fly=true)=>{setSelectedId(id);if(fly)setFocusKey(k=>k+1);if(window.innerWidth<760)setMobilePanel('sage');};
 const analysis=selected&&station?explainCell(selected,station,HORIZONS[index]):[];
 const modeName={receptivity:'Fire receptivity',spread:'Spread potential',moisture:'Fine fuel moisture',vegetation:'Vegetation'}[metric];
 return <main className="r-workspace">
  <Map data={data} index={index} metric={metric} stations={showStations} wind={showWind} official={showOfficial} selected={selected} onSelect={id=>select(id,false)} focusKey={focusKey}/>
  <header className="r-header"><a className="r-brand" href="/" aria-label="GINGER home"><img src="/ginger-symbol.svg" alt=""/><span>GINGER</span></a><div className="r-product"><span className="r-divider"/><b>Fire receptivity intelligence</b><span className="r-region">BARCELONA · CATALUNYA</span></div><div className="r-header-actions"><span className={'r-connection '+(isStale||error?'degraded':'')}><i/>{!data?'CONNECTING':isStale?'STALE OBSERVATIONS':error?'REFRESH DEGRADED':'LIVE DATA'}</span><button onClick={()=>setSources(true)}><Database size={15}/><span>Sources & model</span></button><button className={loading?'r-refresh spinning':'r-refresh'} aria-label="Refresh live data" onClick={()=>void refresh()} disabled={loading}><RefreshCw size={16}/></button></div></header>
  <section className="r-context"><div><p className="r-eyebrow">SAGE / LIVE FIRE ENVIRONMENT</p><h1>Barcelona, right now.</h1><p>If an ignition occurs, how receptive is the vegetation to fire?</p></div><div className="r-summary"><div><b>{data?data.areaKm2.toLocaleString():'—'}</b><span>km² covered</span></div><div><b>{data?data.counts.assessed.toLocaleString():'—'}</b><span>vegetated cells assessed</span></div><div className="r-coverage"><b>{data?data.stations.length:'—'}</b><span>XEMA stations · 200 m cells</span></div></div></section>
  {(error||isStale)&&<div className="r-status-warning" role="status">{isStale?'Historical snapshot — observations are stale. ':''}{error} Scores below retain their original observation times.</div>}
  <aside className={'r-ranking r-panel '+(mobilePanel==='rank'?'r-mobile-open':'')}>
   <div className="r-panel-title"><span>FIRE RECEPTIVITY</span><span className="r-live-dot"/><button className="r-mobile-close" aria-label="Close ranking" onClick={()=>setMobilePanel(null)}><X size={16}/></button></div>
   <div className="r-ranking-head"><h2>{ranking==='hotspots'?'Most receptive areas':'Emerging hotspots'}</h2><p>{data?`${index?`Forecast +${HORIZONS[index]}H`:'Observed NOW'} · ${isStale?'stale snapshot':'computed '+stamp(data.generatedAt)}`:'Connecting to environmental sources…'}</p></div>
   <div className="r-switch"><button aria-pressed={ranking==='hotspots'} onClick={()=>setRanking('hotspots')}>Highest now{index?' / forecast':''}</button><button aria-pressed={ranking==='emerging'} onClick={()=>setRanking('emerging')}>Getting worse <ArrowUpRight size={12}/></button></div>
   <ol className="r-rank-list">{sorted.map((c,i)=><li key={c.id}><button className={selectedId===c.id?'selected':''} onClick={()=>select(c.id)}><span className="r-rank-number">{String(i+1).padStart(2,'0')}</span><span className="r-rank-name"><strong>{c.name}</strong><small>{ranking==='emerging'?`+${fmt(c.velocity)} pts / hour · next 3H`:classificationLabel(c.receptivity[index]!)}<span>{c.center[1].toFixed(3)}° N · {c.center[0].toFixed(3)}° E</span></small></span><b style={{color:color(c.receptivity[index])}}>{c.receptivity[index]}</b><ChevronRight size={13}/></button></li>)}</ol>
   {!data&&<div className="r-loading" role="status"><span className="spinner"/>Preparing the live assessment. First load retrieves station history; this can take a few minutes.</div>}
   {data&&!sorted.length&&<div className="r-empty">{ranking==='emerging'?'No assessed cells are forecast to rise over the next three hours.':'No assessed cells available for this time.'}</div>}
   <div className="r-ranking-foot"><Activity size={14}/><p>Ranked from computed cells. Nearby results are grouped to show distinct areas.</p></div>
   <div className="r-meaning"><b>A condition index. Never an ignition probability.</b><p>Scores describe fuel receptivity if an ignition source is present. Display bands are experimental.</p></div>
  </aside>
  <div className="r-layer-anchor"><button className={'r-layers-toggle '+(layers?'active':'')} aria-expanded={layers} onClick={()=>setLayers(!layers)}><Layers3 size={16}/>{modeName}</button>{layers&&<section className="r-layer-menu r-panel"><div className="r-panel-title">MAP LAYERS<button aria-label="Close layers" onClick={()=>setLayers(false)}><X size={15}/></button></div><Link className="r-prevention-link" href="/prevention">Prevention opportunities <ArrowUpRight size={14}/></Link><fieldset><legend>Cell layer</legend>{(['receptivity','spread','moisture','vegetation'] as Metric[]).map(m=><label key={m}><input type="radio" name="metric" checked={metric===m} onChange={()=>setMetric(m)}/>{{receptivity:'Fire Receptivity',spread:'Spread Potential',moisture:'Fuel Moisture',vegetation:'Vegetation'}[m]}</label>)}</fieldset><label><input type="checkbox" checked={showWind} onChange={e=>setShowWind(e.target.checked)}/>Wind</label><label><input type="checkbox" checked={showStations} onChange={e=>setShowStations(e.target.checked)}/>Weather Stations</label><label><input type="checkbox" checked={showOfficial} disabled={!data?.official.comparable} onChange={e=>setShowOfficial(e.target.checked)}/>Official Fire Danger · Pla Alfa</label>{!data?.official.comparable&&<p>Official current levels cannot be verified. See Sources.</p>}</section>}</div>
  <aside className={'r-sage r-panel '+(mobilePanel==='sage'?'r-mobile-open':'')}>
   <div className="r-panel-title"><span className="r-sage-mark">✳</span><b>SAGE</b><span className="r-engine-tag">ENVIRONMENT ENGINE</span><button className="r-mobile-close" aria-label="Close SAGE analysis" onClick={()=>setMobilePanel(null)}><X size={16}/></button></div>
   <div className="r-sage-scroll">{selected&&station?<>
    <div className="r-sage-location"><p className="r-eyebrow">CELL ASSESSMENT · {index?`+${HORIZONS[index]}H FORECAST`:'CURRENT OBSERVATIONS'}</p><h2>{selected.name}</h2><p>{selected.center[1].toFixed(4)}° N · {selected.center[0].toFixed(4)}° E</p></div>
    <div className="r-scores"><div><span>FIRE RECEPTIVITY</span><strong style={{color:color(score)}}>{score??'—'}<small>/ 100</small></strong><b style={{color:color(score)}}>{score===null?'UNAVAILABLE':classificationLabel(score)}</b></div><div><span>SPREAD POTENTIAL</span><strong>{selected.spread[index]??'—'}<small>/ 100</small></strong><b>{selected.spread[index]===null?'UNAVAILABLE':classificationLabel(selected.spread[index]!)}</b></div></div>
    <div className="r-velocity"><Activity size={17}/><div><span>RECEPTIVITY VELOCITY</span><b>{selected.velocity===null?'Unavailable':`${selected.velocity>0?'+':''}${selected.velocity.toFixed(1)} pts / hour`}</b></div><small>{selected.velocity===null?'Forecast missing':selected.velocity>10?'RAPIDLY RISING':selected.velocity>1?'RISING':selected.velocity< -1?'EASING':'STABLE'}<br/>next 3 hours</small></div>
    <div className="r-spark"><svg viewBox="0 0 300 62" role="img" aria-label="Receptivity forecast over 24 hours"><line x1="4" y1="56" x2="296" y2="56" stroke="#344044"/><polyline points={selected.receptivity.map((v,i)=>v===null?'':`${8+i*56},${56-v*.48}`).filter(Boolean).join(' ')} fill="none" stroke="#c6b987" strokeWidth="2"/>{selected.receptivity.map((v,i)=>v===null?null:<circle key={i} cx={8+i*56} cy={56-v*.48} r={index===i?4:2} fill={index===i?'#f0dfb3':'#7e8e83'}/>)}</svg><div>{HORIZONS.map((h,i)=><button key={h} aria-label={`Show ${h?`plus ${h} hours`:'now'}`} className={index===i?'active':''} onClick={()=>{setIndex(i);setPlaying(false);}}><span>{h?`+${h}H`:'NOW'}</span><b>{selected.receptivity[i]??'—'}</b></button>)}</div></div>
    <section className="r-factors"><h3>What drives this assessment</h3><dl>{[
     ['Fine-fuel moisture',fmt(assessment?.fineFuelMoisture,'% dry mass')],['Relative humidity',fmt(assessment?.conditions.relativeHumidity,'%')],['Rain · previous 1H',fmt(station.history.rain1h,' mm')],['Rain · previous 24H',fmt(station.history.rain24h,' mm')],['Rain · previous 3 days',fmt(station.history.rain3d,' mm')],['Rain · previous 7 days',fmt(station.history.rain7d,' mm')],['Rain · previous 30 days',fmt(station.history.rain30d,' mm')],['Temperature',fmt(assessment?.conditions.temperature,'°C')],['Wind / gusts',`${fmt(assessment?.conditions.windSpeed)} / ${fmt(assessment?.conditions.windGust)} km/h`],['Mapped vegetation',`${Math.round(selected.fuel.burnableFraction*100)}% · ${selected.fuel.type}`],['NDVI / NDMI',`${fmt(selected.fuel.ndvi)} / ${fmt(selected.fuel.ndmi)}`],['Slope / aspect',`${fmt(selected.terrain.slope,'°')} / ${fmt(selected.terrain.aspect,'°')}`]
    ].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>
    <section className="r-analysis"><h3><span>✳</span> SAGE ANALYSIS</h3>{analysis.map((line,i)=><p key={i}>{line}</p>)}</section>
    <details className="r-evidence"><summary>Evidence & limitations <span>{selected.confidenceLabel.toUpperCase()}</span></summary><p>Evidence completeness {Math.round(selected.confidence*100)}/100. This is a documented quality heuristic, not a statistical confidence probability.</p><p>Observed: {fullStamp(station.frames[0].timestamp)}<br/>Station: {station.station.name}<br/>Forecast source: {station.forecastSource||'Unavailable'}<br/>Forecast issue: {fullStamp(station.forecastIssuedAt)}</p><p>Land cover: {selected.fuel.source}. {selected.fuel.satelliteAt?`Satellite: ${fullStamp(selected.fuel.satelliteAt)}.`:'Current satellite moisture unavailable.'}</p>{station.quality.map(q=><p key={q}>{q}</p>)}<p>24H mean / minimum RH: {fmt(station.history.humidityMean24h,'%')} / {fmt(station.history.humidityMin24h,'%')}. Soil moisture, recent ET and measured live/dead fuel loads are unavailable.</p><code>{selected.id}</code></details>
   </>:<div className="r-loading"><Flame size={23}/><p>Select a vegetated cell to inspect its environmental conditions and the calculation behind its score.</p></div>}</div>
  </aside>
  <div className="r-map-legend"><span>{modeName.toUpperCase()}</span>{metric==='vegetation'?<p>Tree cover · shrubland · grassland · cropland</p>:metric==='moisture'?<p><i style={{background:'#ed974f'}}/>Very dry &lt;10%<i style={{background:'#5b9696'}}/>Moister fuels</p>:<p>{[[20,'Low'],[50,'Moderate'],[70,'High'],[85,'Very high'],[95,'Extreme']].map(([n,label])=><span key={label}><i style={{background:color(Number(n))}}/>{label}</span>)}</p>}</div>
  <nav className="r-timeline" aria-label="Receptivity forecast timeline"><button className="r-play" aria-label={playing?'Pause timeline':'Animate timeline'} disabled={!data} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><div className="r-time-label"><span>ENVIRONMENT FORECAST</span><small>{index?'Weather forecast · current fuel map':'Latest station observations'}</small></div><div className="r-time-stops">{HORIZONS.map((h,i)=><button key={h} aria-pressed={index===i} disabled={!!data&&!data.stations.some(s=>s.frames.some(f=>f.horizon===h))} onClick={()=>{setIndex(i);setPlaying(false);}}>{h?`+${h}H`:'NOW'}</button>)}</div></nav>
  <div className="r-mobile-nav"><button onClick={()=>setMobilePanel(mobilePanel==='rank'?null:'rank')}>Areas <ChevronRight size={14}/></button><button onClick={()=>setMobilePanel(mobilePanel==='sage'?null:'sage')}>SAGE analysis <ChevronRight size={14}/></button></div>
  <footer className="r-footer"><span><i/>{data?`COMPUTED ${ago(data.generatedAt,now).toUpperCase()}`:'ACQUIRING LIVE DATA'}<b>{data?.observationRange?`XEMA ${stamp(data.observationRange.oldest)}–${stamp(data.observationRange.newest)} · Europe/Madrid`:''}</b></span><span>Conditional receptivity · not fire occurrence prediction</span></footer>
  {sources&&<Modal title="Sources, freshness & method" subtitle="SAGE · Barcelona fire environment" onClose={()=>setSources(false)} wide><div className="r-source-body"><p className="r-source-intro">GINGER estimates how receptive mapped vegetation is to establishing fire if an ignition occurs. It does not predict whether or when an ignition source will occur.</p>{data?.sources.map(s=><article key={s.id}><div><h3>{s.name}</h3><span data-status={s.status}>{s.status.toUpperCase()}</span></div><p>{s.detail}</p><small>{s.validAt?`Source time ${fullStamp(s.validAt)} · `:''}{s.refreshMinutes?`Refresh ${s.refreshMinutes} min`:'Static / periodic layer'}</small><a href={s.url} target="_blank" rel="noreferrer">Provider documentation <ArrowUpRight size={12}/></a></article>)}<article><h3>Deterministic model · version {data?.version||'1.0'}</h3><p>Hourly/subhourly FFMC models the moisture balance of dead fine litter using observed temperature, humidity, 10 m wind and precipitation. Thirty days of station history are fetched; at least 48 uninterrupted hours are required after initialization.</p><p>Fire Receptivity = clamp((FFMC − 60) / 40 × 100). This transparent display scale emphasizes the dry end of FFMC. Its bands are GINGER labels, not calibrated probabilities or official Catalan danger classes. A score of zero does not establish that combustion is impossible.</p><p>Spread Potential = 100 × ISI / (ISI + 20). ISI combines FFMC and wind. The display reference of 20 is a documented UI choice. It is not a propagation speed. Terrain, continuity and satellite moisture are exposed as context; unknown fuel loads prevent a defensible terrain-adjusted spread model.</p><p>FWI itself is not reported: it also requires daily DMC/DC/BUI states and represents intensity potential, a different quantity. Catalan validation and fuel-specific calibration remain outstanding.</p><a href="/methodology" target="_blank" rel="noreferrer">Read model and data methodology <ArrowUpRight size={12}/></a></article>{data?.warnings.map(w=><p className="r-source-warning" key={w}>{w}</p>)}</div></Modal>}
 </main>;
}
