import assert from 'node:assert/strict';
import {classifyHeatwave,heatThreshold,localDate,parseHeatForecast,parseMetHeat,type HeatForecast} from '../../src/lib/receptivity/heatwave';
import {assessCellEvidence,freshThermal,vegetationSignal,type SatelliteEvidence} from '../../src/lib/receptivity/satellite-evidence';
import {parseHotspots} from '../../src/lib/providers/deepfire';
import {providerFailure} from '../../src/lib/providers/http';
import type {GridCell} from '../../src/lib/receptivity/types';
const now=Date.parse('2026-09-19T12:00:00Z'),threshold=heatThreshold('Barcelona')!;
assert(threshold>30&&threshold<40);assert.equal(heatThreshold('invented municipality'),null);
assert.equal(localDate(Date.parse('2026-09-19T23:30:00Z')),'2026-09-20');
function forecast(values:(number|null)[]):HeatForecast{return {status:'live',retrievedAt:new Date(now).toISOString(),days:values.map((maximumC,i)=>({date:new Date(now+(i-3)*86400000).toISOString().slice(0,10),maximumC,kind:i<3?'modelled-history':'forecast'}))};}
const mild=forecast(Array(10).fill(20));
assert.equal(classifyHeatwave('a','Barcelona',mild,now).status,'none');
const hot=classifyHeatwave('a','Barcelona',forecast([20,20,20,threshold+.1,threshold+1,threshold+2,20,20,20,20]),now);
assert.equal(hot.status,'ongoing');assert.equal(hot.episodes[0].days,3);assert.equal(hot.episodes[0].start,'2026-09-19');
assert.equal(classifyHeatwave('a','Barcelona',forecast(Array(10).fill(threshold)),now).episodes.length,0,'Strict threshold exceedance');
assert.equal(classifyHeatwave('a','Barcelona',forecast([20,20,20,20,threshold+1,threshold+2,threshold+3,20,20,20]),now).status,'forecast');
const gap=forecast(Array(10).fill(threshold+1));gap.days[4].maximumC=null;
assert.equal(classifyHeatwave('a','Barcelona',gap,now).episodes.length,2,'Missing day splits episodes');
const incomplete=forecast(Array(10).fill(20));incomplete.days.splice(4,1);
assert.equal(classifyHeatwave('a','Barcelona',incomplete,now).status,'incomplete');
assert.equal(classifyHeatwave('a','Barcelona',{...mild,status:'unavailable'},now).status,'unavailable');
assert.equal(classifyHeatwave('a','unknown',mild,now).status,'unavailable');
assert.equal(classifyHeatwave('a','Barcelona',forecast([threshold+1,threshold+1,threshold+1,20,20,20,20,20,20,20]),now).status,'none','Past episode is not an active warning');
assert.throws(()=>parseHeatForecast({timezone:'UTC',daily:{time:[],temperature_2m_max:[]}},now));
const raw={timezone:'Europe/Madrid',daily_units:{temperature_2m_max:'°C'},daily:{time:['2026-09-18','2026-09-19'],temperature_2m_max:[null,34]}};
assert.equal(parseHeatForecast(raw,now).days[0].maximumC,null);assert.equal(parseHeatForecast(raw,now).days[0].kind,'modelled-history');
assert.throws(()=>parseHeatForecast({...raw,daily:{time:['2026-09-19','2026-09-19'],temperature_2m_max:[34,35]}},now));
const met={properties:{meta:{updated_at:new Date(now-3600000).toISOString(),units:{air_temperature:'celsius',air_temperature_max:'celsius'}},timeseries:[{time:'2026-09-19T18:00:00Z',data:{instant:{details:{air_temperature:20}},next_6_hours:{details:{air_temperature_max:55}}}},{time:'2026-09-20T10:00:00Z',data:{instant:{details:{air_temperature:30}},next_6_hours:{details:{air_temperature_max:35}}}}]}};
const fallback=parseMetHeat(met,[],now);
assert.equal(fallback.days.find(d=>d.date==='2026-09-19')?.maximumC,20,'Cross-midnight interval maximum is excluded');
assert.equal(fallback.days.find(d=>d.date==='2026-09-20')?.maximumC,35,'Same-day interval maximum is used');
assert.equal(classifyHeatwave('a','Barcelona',fallback,now).status,'incomplete','Partial low readings cannot assert no episode');
assert.throws(()=>parseMetHeat({...met,properties:{...met.properties,meta:{...met.properties.meta,updated_at:'2026-09-18T00:00:00Z'}}},[],now));
const observations=parseHotspots({type:'FeatureCollection',features:[{id:'a',type:'Feature',geometry:{type:'Point',coordinates:[2.1,41.4]},properties:{observed_at:new Date(now-3600000).toISOString(),source:'MTG',fire_radiative_power:42,brightness:320,confidence:'HIGH'}}]});
assert.equal(observations[0].raw?.brightness,320);assert.equal(observations[0].frpMw,42);
const satellite:SatelliteEvidence={status:'live',source:'Deepfire',retrievedAt:new Date(now).toISOString(),detail:'test',observations};
const cell:GridCell={id:'test',center:[2.1,41.4],ring:[],terrain:{},fuel:{type:'Tree cover',burnableFraction:1,continuity:1,fractions:{},source:'test',epoch:'2026',ndmi:-.1,ndvi:.6,satelliteCoverage:.8,satelliteAt:new Date(now-86400000).toISOString()}};
const noHeat=classifyHeatwave('a','Barcelona',mild,now);
assert.equal(assessCellEvidence(cell,80,noHeat,satellite,now).priority,'urgent');
assert.equal(assessCellEvidence(cell,30,noHeat,satellite,now).priority,'review');
assert.equal(assessCellEvidence(cell,30,noHeat,{...satellite,observations:[]},now).priority,'routine');
assert.equal(assessCellEvidence(cell,30,noHeat,{...satellite,status:'unavailable',observations:[]},now).priority,'unknown');
assert.equal(assessCellEvidence(cell,30,hot,{...satellite,observations:[]},now).priority,'review');
assert.equal(assessCellEvidence(cell,80,noHeat,{...satellite,observations:[]},now).priority,'review','Spectral signal used with high receptivity');
assert.equal(vegetationSignal({...cell.fuel,satelliteAt:new Date(now-11*86400000).toISOString()},now),'stale');
assert.equal(vegetationSignal({...cell.fuel,satelliteCoverage:.49},now),'unavailable');
assert.equal(vegetationSignal({...cell.fuel,ndvi:.1},now),'available','Bare surfaces do not trigger vegetation dryness');
assert.equal(freshThermal([...observations,...observations],now).length,1);
assert.equal(freshThermal(observations.map(h=>({...h,provenance:{...h.provenance,observedAt:new Date(now+1).toISOString()}})),now).length,0);
assert.equal(assessCellEvidence({...cell,fuel:{...cell.fuel,ndmi:undefined}},80,noHeat,{...satellite,retrievedAt:new Date(now-31*60000).toISOString()},now).priority,'unknown','Stale source cannot trigger');
assert.equal(providerFailure(new Error('secret upstream payload')),'Request failed or data was incomplete');
console.log('PASS heatwave thresholds, 3-day episodes, missing dates, Madrid dates, provenance, raw satellite fields, spatial priority, stale/future/duplicate suppression, and clear-pixel vegetation gating');
