'use client';
import {wildfireReferenceText} from '@/lib/wildfire-references';
import WildfireReferences from './wildfire-references';
import {useMemo,useState} from 'react';
import type {Assessment} from '@/lib/assessment';
import type {PreparedArea} from '@/lib/prepared-workspace';
import {EvidenceBadge} from './evidence';
import {deriveIntelligence} from '@/lib/intelligence';
export default function IntelligencePanel({assessment,name,prepared}:{assessment:Assessment;name:string;prepared?:PreparedArea|null}){
 const report=useMemo(()=>prepared?.report??deriveIntelligence(assessment),[assessment,prepared]);const [exported,setExported]=useState(false);
 function download(){const text=`GINGER // SAGE — ${name}\nGenerated ${assessment.generatedAt}\nRules-based decision support\n\n${report.briefing}\n\nEVIDENCE\n${report.evidence.map(e=>`[${e.id}] ${e.label}: ${e.value} | ${e.source} | ${e.time}`).join('\n')}\n\nLIMITATIONS\n${report.limitations.join('\n')}`;const url=URL.createObjectURL(new Blob([text+wildfireReferenceText()],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=`ginger-briefing-${new Date().toISOString().slice(0,10)}.txt`;a.click();URL.revokeObjectURL(url);setExported(true);}
 return <div className="upgrade-panel intelligence-panel"><div className="upgrade-intro"><EvidenceBadge kind="derived" detail="Rules-based interpretation"/><span className="eyebrow">EVIDENCE → ASSESSMENT → ATTENTION</span><h3>{report.headline}</h3><p>Rules-based analysis of the selected area's inputs. Generated {new Date(assessment.generatedAt).toLocaleString()}.</p></div><div className="briefing-copy">{prepared?.ai&&prepared.aiStatus==='ready'?<><p>{prepared.ai.answer}</p><small>Astra · prepared {new Date(prepared.ai.generatedAt).toLocaleString()} · evidence {new Date(prepared.ai.evidenceAt).toLocaleString()}</small><details><summary>AI sources</summary>{prepared.ai.sources.map(source=><p key={source.id}>[{source.id}] {source.source} · {source.status} · {new Date(source.retrievedAt).toLocaleString()}</p>)}</details></>:report.briefing}</div><div className="upgrade-actions">{report.actions.map((a,i)=><article key={a.id}><span className="action-index">{String(i+1).padStart(2,'0')}</span><div><h4>{a.title}</h4><p>{a.reason}</p><div className="evidence-links">{a.evidenceIds.map(id=><a href={`#evidence-${id}`} key={id}>[{id}]</a>)}</div></div></article>)}</div>{report.weatherWindows.length>0&&<section className="upgrade-section"><EvidenceBadge kind="simulated" detail="Calculated from modelled weather"/><h3>Weather windows to watch</h3>{report.weatherWindows.map((w,i)=><div className="weather-window" key={i}><time>{new Date(w.start).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}–{new Date(w.end).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time><div><b>{w.label}</b><p>{w.reason}</p></div></div>)}</section>}<section className="upgrade-section"><h3>The evidence</h3><div className="evidence-table">{report.evidence.map(e=><div id={`evidence-${e.id}`} key={e.id}><span>[{e.id}]</span><div><EvidenceBadge kind={e.id==='LATEST'?'observed':e.id==='PEAK'?'simulated':'derived'}/><b>{e.label}</b><p>{e.value}</p><small>{e.source} · {e.time}</small></div></div>)}</div></section><details className="upgrade-section"><summary>Assumptions and limitations ({report.limitations.length})</summary>{report.limitations.map((l,i)=><p key={i}>{l}</p>)}</details><WildfireReferences/><button className="primary-button" onClick={download}>{exported?'Export again':'Export cited briefing'}</button></div>;
}
