'use client';
import {useEffect,useState,useMemo,useCallback} from 'react';
import dynamic from 'next/dynamic';
import {RefreshCw,Flame,Wind,Building2,Satellite,ArrowUpRight,Activity,Layers3} from 'lucide-react';
import type {Hotspot} from '@/lib/providers/types';
import type {FeatureCollection} from 'geojson';
import type {MapData} from './operational-map';
import Modal from './modal';
import {EvidenceBadge,EvidenceKey} from './evidence';
const Map=dynamic(()=>import('./operational-map'),{ssr:false});
type Snapshot={region:string;retrievedAt:string;satelliteRetrievedAt:string|null;latestObservation:string|null;hotspots:Hotspot[];weather:{data:{temperature:number;humidity:number;windKmh:number;windDirection:number};detail:string;updatedAt:string}|null;assets:FeatureCollection;statuses:{id:string;name:string;status:string;detail:string;url:string}[]};
const centers={catalonia:{center:[1.83,41.5] as [number,number],zoom:8},iberia:{center:[-3,40] as [number,number],zoom:5.5},europe:{center:[12,49] as [number,number],zoom:5}};
const stamp=(s:string|null|undefined)=>s?new Date(s).toLocaleString('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})+' UTC':'Unknown';
export default function LiveCenter({onDemo}:{onDemo:()=>void}){
 const [region,setRegion]=useState<keyof typeof centers>('catalonia'),[data,setData]=useState<Snapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<string|null>(null),[panel,setPanel]=useState<'detections'|'assets'>('detections'),[dialog,setDialog]=useState<'sources'|'briefing'|null>(null),[feed,setFeed]=useState(false),[delta,setDelta]=useState('Initial observation snapshot');
 const [focus,setFocus]=useState({...centers.catalonia,key:0});
 const refresh=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError('');try{const r=await fetch(`/api/live?region=${region}`,{signal:signal||AbortSignal.timeout(30000)});if(!r.ok)throw Error();const next:Snapshot=await r.json();setData(prev=>{if(prev&&prev.region===next.region){const ids=new Set(prev.hotspots.map(h=>h.id));const count=next.hotspots.filter(h=>!ids.has(h.id)).length;setDelta(`${count} new detections since the previous snapshot`);}else setDelta('Initial observation snapshot');return next;});}catch{if(!signal?.aborted)setError('Live connection failed. Previous observations, if shown, are retained and may be stale.');}finally{if(!signal?.aborted)setLoading(false);}},[region]);
 useEffect(()=>{const c=new AbortController();void refresh(c.signal);const id=setInterval(()=>void refresh(c.signal),600000);return()=>{c.abort();clearInterval(id);};},[refresh]);
 const hotspot=data?.hotspots.find(h=>h.id===selected);const asset=data?.assets.features.find(f=>String(f.properties?.id)===selected);const weather=data?.weather?.data;
 const mapData=useMemo<MapData>(()=>({perimeter:[],envelopes:[],routes:[],risk:[],cameras:[],wind:[],hotspots:data?.hotspots.map(h=>({type:'Feature',geometry:{type:'Point',coordinates:h.position},properties:{id:h.id}}))||[],assets:data?.assets.features||[]}),[data]);
 const select=(id:string,p:[number,number])=>{setSelected(id);setFocus(f=>({center:p,zoom:12,key:f.key+1}));};
 const connected=data?.statuses.filter(s=>s.status==='live').length||0;
 return <div className="app-shell live-shell"><header className="topbar"><div className="brand"><span className="brand-mark"><img src="/ginger-symbol.svg" alt=""/></span><span className="brand-name" role="img" aria-label="ginger"/><span className="brand-divider"/><span className="brand-subtitle">WILDFIRE INTELLIGENCE SUITE</span></div><div className="topbar-center"><strong>prevent</strong><span>/</span><strong>predict</strong><span>/</span><strong>protect</strong></div><div className="topbar-actions"><div className="mode-switch"><button className="active" aria-pressed="true">LIVE</button><button onClick={onDemo}>DEMO</button></div><div className="top-clock">{connected}/3 <small>SOURCES CONNECTED</small></div></div></header>
 <nav className="navrail" aria-label="Live navigation"><button className={panel==='detections'?'active':''} onClick={()=>{setPanel('detections');setSelected(null);}}><Satellite size={20}/><span>Detections</span></button><button className={panel==='assets'?'active':''} onClick={()=>{setPanel('assets');setSelected(null);}}><Building2 size={20}/><span>Assets</span></button><button onClick={()=>setDialog('briefing')}><Activity size={20}/><span>Briefing</span></button><div className="nav-spacer"/><button onClick={()=>setDialog('sources')}><Layers3 size={20}/><span>Sources</span></button></nav>
 <main className="workspace"><div className="workspace-head"><div><h1>Live observation desk</h1><p>Satellite evidence · regional bounding-box coverage.</p></div><div className="head-actions"><select className="region-select" aria-label="Observation region" value={region} onChange={e=>{const r=e.target.value as keyof typeof centers;setRegion(r);setData(null);setSelected(null);setFocus(f=>({...centers[r],key:f.key+1}));}}><option value="catalonia">Catalonia</option><option value="iberia">Iberia</option><option value="europe">Europe</option></select><button className="secondary-button" onClick={()=>void refresh()} disabled={loading}><RefreshCw size={14}/>{loading?'Connecting…':'Refresh'}</button><button className="mobile-feed-toggle icon-button" aria-label="Toggle live feed" onClick={()=>setFeed(!feed)}><Activity size={18}/></button></div></div>
 <EvidenceKey/><section className="metrics">{[{label:'THERMAL DETECTIONS',value:data?.statuses.find(s=>s.id==='fire')?.status==='live'||data?.statuses.find(s=>s.id==='fire')?.status==='stale'?String(data.hotspots.length):'—',note:'Public 24-hour satellite file',icon:Flame},{label:'GARRAF WIND',value:weather?`${weather.windKmh} km/h`:'—',note:weather?`${weather.windDirection}° · modelled weather`:'Weather unavailable',icon:Wind},{label:'MAPPED ASSETS',value:data?.statuses.find(s=>s.id==='assets')?.status==='live'?String(data.assets.features.length):'—',note:'Garraf · OpenStreetMap inventory',icon:Building2},{label:'LATEST SATELLITE',value:data?.latestObservation?new Date(data.latestObservation).toISOString().slice(11,16):'—',note:stamp(data?.latestObservation),icon:Satellite}].map(m=><div className="metric evidence-card" data-evidence={m.label==='GARRAF WIND'?'simulated':'derived'} key={m.label}><div><EvidenceBadge kind={m.label==='GARRAF WIND'?'simulated':'derived'}/><div className="metric-title">{m.label}</div><div className="metric-value amber-text" style={{fontSize:25}}>{m.value}</div></div><div className="metric-side"><m.icon size={17}/><small>{m.note}</small></div></div>)}</section>
 <section className="map-stage"><Map data={mapData} focus={focus} onSelect={(kind,id,p)=>{if(kind==='hotspots'||kind==='assets')select(id,p);}} mode="live" forecast={0} incidentActive={false}/>
 <aside className="left-panel panel"><div className="panel-heading">{hotspot?'Satellite observation':asset?'Mapped infrastructure':panel==='assets'?'Garraf infrastructure':'Satellite detections'}<EvidenceBadge kind="observed"/></div>
 {hotspot?<div className="incident-detail"><button className="back-button" onClick={()=>setSelected(null)}>← All detections</button><h2 style={{fontSize:19}}>Thermal anomaly</h2><p className="detail-location">{hotspot.position[1].toFixed(5)}° N · {hotspot.position[0].toFixed(5)}° E</p><div className="detail-grid"><div><span>RADIATIVE POWER</span><b>{hotspot.frpMw??'—'} <small>MW</small></b></div><div><span>CONFIDENCE</span><b style={{fontSize:17}}>{hotspot.confidence}</b></div></div><p className="small-source">Observed {stamp(hotspot.provenance.observedAt)}<br/>{hotspot.provenance.source}</p><div className="detail-note">A satellite hotspot is not a confirmed wildfire. Industrial heat, agricultural burning and other sources can produce detections. Perimeter, spread and evacuation ETA are unavailable until validated inputs are connected.</div><a className="secondary-button detail-action" target="_blank" rel="noreferrer" href={`https://firms.modaps.eosdis.nasa.gov/map/#d:24hrs;@${hotspot.position[0]},${hotspot.position[1]},12z`}>Inspect in NASA FIRMS <ArrowUpRight size={13}/></a></div>
 :asset?<div className="incident-detail"><button className="back-button" onClick={()=>setSelected(null)}>← All assets</button><h2 style={{fontSize:18}}>{String(asset.properties?.name)}</h2><p className="small-source">{String(asset.properties?.kind)} · OpenStreetMap</p><div className="detail-note">Population, evacuation capacity and fire arrival are unknown. No modelled safety margin is shown for this real asset.</div></div>
 :<div className="feed-scroll">{loading&&!data?<div className="empty-state">Fetching satellite observations…</div>:panel==='detections'?data?.hotspots.length?data.hotspots.map(h=><button className="incident-card" key={h.id} onClick={()=>select(h.id,h.position)}><div className="card-top"><span className="incident-id">VIIRS · THERMAL DETECTION</span><span className="badge high">{h.confidence}</span></div><h3>{h.position[1].toFixed(3)}° N, {h.position[0].toFixed(3)}° E</h3><p className="location">{stamp(h.provenance.observedAt)}</p><div className="card-bottom"><span>{h.frpMw??'Unknown'} MW</span><ArrowUpRight size={13}/></div></button>):<div className="empty-state">{data?.statuses[0]?.status==='unavailable'?'Satellite feed unavailable.':'No detections returned in this region. This does not establish the absence of fire.'}</div>:data?.assets.features.length?data.assets.features.map(f=><button className="incident-card" key={String(f.properties?.id)} onClick={()=>{if(f.geometry.type==='Point')select(String(f.properties?.id),f.geometry.coordinates.slice(0,2) as [number,number]);}}><h3>{String(f.properties?.name)}</h3><p className="location">{String(f.properties?.kind)} · OpenStreetMap</p></button>):<div className="empty-state">Infrastructure feed unavailable or empty. No synthetic assets are substituted.</div>}</div>}
 </aside>
 <aside className={'right-panel panel '+(feed?'mobile-open':'')}><div className="panel-heading">Observation intelligence<button className="mobile-only" onClick={()=>setFeed(false)}>Close</button></div><div className="feed-scroll">{error&&<div className="detail-note red-text">{error}</div>}<article className="feed-entry"><span className="badge watch">SOURCE UPDATE</span><h3 style={{marginTop:12}}>{delta}</h3><p>Retrieved {stamp(data?.satelliteRetrievedAt)}. Refresh interval: 10 minutes.</p></article><article className="feed-entry"><h3>Garraf weather</h3><p>{weather?`${weather.temperature}°C · ${weather.humidity}% humidity · ${weather.windKmh} km/h wind`:'No weather observation available.'}</p><p className="small-source">{data?.weather?.detail}</p></article>{data?.statuses.map(s=><article className="feed-entry" key={s.id}><div className="feed-entry-top"><h3>{s.name}</h3><span className={'badge '+(s.status==='live'?'watch':'high')}>{s.status.toUpperCase()}</span></div><p>{s.detail}</p></article>)}</div><div className="feed-bottom"><button onClick={()=>setDialog('briefing')}>Generate observation briefing <ArrowUpRight size={15}/></button></div></aside>
 <div className="forecast-panel panel"><div><b>Observed data · no simulated forecasts</b><p className="small-source">Perimeters, fire arrival and evacuation margins require validated model inputs. Camera feeds are not connected.</p></div></div>
 </section></main><footer className="bottom-bar"><span>{loading?'FETCHING SOURCES':error?'CONNECTION DEGRADED':connected===3?'LIVE SOURCES CONNECTED':'PARTIAL SOURCE COVERAGE'}</span><span>LIVE OBSERVATIONS · {stamp(data?.retrievedAt)}</span></footer>
 {dialog&&<Modal title={dialog==='sources'?'Connected sources':'Observation briefing'} onClose={()=>setDialog(null)}><div className="modal-body">{dialog==='sources'?data?.statuses.map(s=><div className="provider-row" key={s.id}><h3>{s.name} · {s.status}</h3><p>{s.detail}</p><a href={s.url} target="_blank" rel="noreferrer">Source documentation ↗</a></div>):<><p>{data?.hotspots.length??0} thermal detections were returned for {region} from the satellite file. Latest source observation: {stamp(data?.latestObservation)}.</p><p className="small-source">[1] NASA FIRMS / configured Deepfire feed · retrieved {stamp(data?.satelliteRetrievedAt)}</p><p>{weather?`Garraf modelled weather is ${weather.temperature}°C, ${weather.humidity}% humidity and ${weather.windKmh} km/h wind.`:'Weather unavailable.'}</p><p className="small-source">[2] {data?.weather?.detail||'Open-Meteo request unavailable'}</p><p>{data?.assets.features.length??0} mapped infrastructure features are available around Garraf. Verify any thermal detection before classifying it as a wildfire. No fire arrival, evacuation margin or safe-route claim can be supported by these observations alone.</p><p className="small-source">[3] OpenStreetMap inventory · no population or road-capacity assumptions</p></>}</div></Modal>}
 </div>;
}
