'use client';
import Link from 'next/link';
import type {MonitorSnapshot} from '@/lib/monitor';
import {preventionOpportunity,type PreventionOpportunity} from '@/lib/prevention-opportunity';

export function OpportunityScore({opportunity:o}:{opportunity:PreventionOpportunity}){
 return <div className="opportunity-score"><div><span className="eyebrow">PREVENTION OPPORTUNITY</span><strong>{o.score===null?'—':o.score}<small>{o.score===null?'Unscored':'/100'}</small></strong><span>{o.label}</span></div><p>Preliminary planning index · effectiveness unvalidated</p>{o.score!==null&&<meter min={0} max={100} value={o.score} aria-label="Prevention opportunity score"/>}<details><summary>Score basis and evidence gaps</summary><p>Evidence coverage + identifiable checks + time to prepare. This index describes supported opportunities to act, not the percentage of fires preventable. It does not estimate ignition probability or risk reduction.</p><ul>{o.factors.map(f=><li key={f.label}><b>{f.label}: {f.points}/{f.maximum}</b><br/>{f.reason}</li>)}</ul>{o.gaps.map(g=><p key={g}>{g}</p>)}</details></div>;
}
export default function PreventionOpportunities({monitor,error,onPlan,onInspect,now}:{now:number;monitor:MonitorSnapshot|null;error:string;onPlan:(lon:number,lat:number,name:string)=>void;onInspect:(lon:number,lat:number,name:string)=>void}){
 const points=(monitor?.zones||[]).map(zone=>({zone,opportunity:preventionOpportunity(zone,now)})).sort((a,b)=>(b.opportunity.score??-1)-(a.opportunity.score??-1)||a.zone.name.localeCompare(b.zone.name));
 return <aside className="prevention-panel panel" aria-label="Prevention opportunities"><header><span className="eyebrow">ACT BEFORE IMPACT</span><h2>Prevention opportunities</h2><p>Where a concrete next check is supported.</p><Link href="/">Fire receptivity ↗</Link></header><div className="prevention-scroll"><p className="opportunity-intro">Teal points locate watch-area centres. Scores describe the surrounding area, not a surveyed intervention site.</p>{error&&<p role="alert">{error}</p>}{!monitor&&<p role="status">Checking prevention evidence…</p>}{monitor&&!points.length&&<p>Add a watch area in Areas to find prevention opportunities.</p>}{points.map(({zone:z,opportunity:o})=><article className="prevention-area opportunity-card" key={z.id}><div className="feed-entry-top"><h3>{z.name}</h3><span className="badge watch">{z.state==='escalating'?'Priority review':z.state==='monitoring'?'Monitoring':z.state==='unavailable'?'Data gap':'Review'}</span></div><OpportunityScore opportunity={o}/><ul className="opportunity-interventions">{o.interventions.map(i=><li key={i.id}><strong>{i.title}</strong><p>{i.reason}</p></li>)}</ul><div className="prevention-card-actions"><button className="secondary-button" onClick={()=>onPlan(z.position[0],z.position[1],z.name)}>Review interventions ↗</button><button className="secondary-button" onClick={()=>onInspect(z.position[0],z.position[1],z.name)}>Inspect area ↗</button></div><small>Area radius {(z.radiusM??15000)/1000} km · evidence {new Date(z.updatedAt).toLocaleString()}</small></article>)}</div></aside>;
}
