'use client';
import {assessmentOpportunity} from '@/lib/prevention-opportunity';
import {OpportunityScore} from './prevention-opportunities';
import WildfireReferences from './wildfire-references';
import {useEffect,useState} from 'react';
import type {Assessment} from '@/lib/assessment';
import type {PreparedArea} from '@/lib/prepared-workspace';
import type {OperationLocation,OperationsState} from '@/lib/operations';
import {buildPreventionPlan} from '@/lib/prevention-plan';
export default function PreventionPlan({location,onTasks,onCompare,prepared}:{prepared?:PreparedArea|null;location:OperationLocation;onTasks:()=>void;onCompare:()=>void}){
 const [assessment,setAssessment]=useState<Assessment|null>(null),[error,setError]=useState(''),[saved,setSaved]=useState<string[]>([]),[busy,setBusy]=useState<string|null>(null);
 useEffect(()=>{const c=new AbortController();setAssessment(null);setError('');setSaved([]);Promise.all([prepared?Promise.resolve(prepared.assessment):fetch(`/api/assessment?lat=${location.lat}&lon=${location.lon}`,{signal:AbortSignal.any([c.signal,AbortSignal.timeout(22000)])}).then(async r=>{if(!r.ok)throw Error('Could not load evidence. Reopen the plan to retry.');return r.json() as Promise<Assessment>;}),fetch('/api/operations',{signal:AbortSignal.any([c.signal,AbortSignal.timeout(22000)]),cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('Could not load saved tasks. Reopen the plan to retry.');return r.json() as Promise<OperationsState>;})]).then(([a,o])=>{if(!c.signal.aborted){setAssessment(a);setSaved(o.tasks.filter(t=>t.status!=='completed'&&t.location.lat===location.lat&&t.location.lon===location.lon).flatMap(t=>t.planId?[t.planId]:[]));}}).catch(e=>{if(!c.signal.aborted)setError(e.name==='TimeoutError'?'Evidence request timed out. Reopen the plan to retry.':e.message);});return()=>c.abort();},[location.lat,location.lon,prepared]);
 async function save(planId:string){setBusy(planId);setError('');try{const r=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create-plan-task',planId,location})});const data=await r.json();if(!r.ok)throw Error(data.error);setSaved(p=>[...p,planId]);}catch(e){setError(e instanceof Error?e.message:'Could not save inspection.');}finally{setBusy(null);}}
 const plan=assessment?buildPreventionPlan(assessment):[];
 return <section className="prevention-plan"><p className="small-source">{location.name} · Evidence-linked work proposals</p>{assessment&&<><OpportunityScore opportunity={assessmentOpportunity(assessment)}/><p className="small-source">Local assessment · {assessment.location.radiusM/1000} km geographic inventory. This can differ from the wider watch-area score.</p></>}{error&&<p role="alert">{error}</p>}{!assessment&&!error&&<p role="status">Building the plan from current evidence…</p>}{(['prevention','assets','coordination'] as const).map(category=><section key={category}><h3>{category==='prevention'?'Prevention':category==='assets'?'Asset checks':'Coordination'}</h3>{plan.filter(p=>p.category===category).map(p=><article className="plan-card" key={p.id}><div className="feed-entry-top"><h4>{p.title}</h4><span className="badge watch">{p.priority}</span></div><p>{p.reason}</p><details><summary>Inspection checklist</summary><ul>{p.checks.map(c=><li key={c}>{c}</li>)}</ul><small>Evidence: {new Date(p.evidenceAt).toLocaleString()}<br/>{p.sourceNames.join(' · ')||'Source gaps recorded'}</small></details><button className="secondary-button" disabled={busy!==null||saved.includes(p.id)} onClick={()=>void save(p.id)}>{saved.includes(p.id)?'In task queue':busy===p.id?'Saving…':'Create inspection'}</button></article>)}</section>)}<WildfireReferences/><div className="prevention-card-actions"><button className="primary-button" onClick={onTasks}>Open task queue ↗</button><button className="secondary-button" onClick={onCompare}>Explore mitigation scenarios ↗</button></div><p className="small-source">Proposals use explicit review rules. Field checks and scenario assumptions remain subject to verification.</p></section>;
}
