'use client';
import {useEffect,useRef,useState} from 'react';
export default function SageExplanation({runId}:{runId:string}){
 const [config,setConfig]=useState<{configured:boolean;provider:string;model:string}>(),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const pending=useRef<AbortController|null>(null);
 useEffect(()=>{const c=new AbortController();fetch('/api/sage/explain',{signal:c.signal}).then(r=>r.ok?r.json():Promise.reject()).then(setConfig).catch(()=>{});return()=>c.abort();},[]);
 useEffect(()=>{setAnswer('');setError('');setBusy(false);pending.current?.abort();return()=>pending.current?.abort();},[runId]);
 async function ask(e:React.FormEvent){e.preventDefault();pending.current?.abort();const c=new AbortController();pending.current=c;setBusy(true);setError('');setAnswer('');try{const r=await fetch('/api/sage/explain',{method:'POST',headers:{'Content-Type':'application/json'},signal:c.signal,body:JSON.stringify({runId,question})});const data=await r.json();if(!r.ok)throw Error(data.error||'Explanation unavailable');if(!c.signal.aborted)setAnswer(data.answer);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Explanation unavailable');}finally{if(!c.signal.aborted)setBusy(false);}}
 return <details className="sage-explanation"><summary>Ask about this simulation</summary><p>Get a plain-language explanation grounded in this run. Suggestions do not change the simulation.</p>{!config?.configured?<p role="status">{config?'Assistant not connected yet. Nebius account setup is pending.':'Checking assistant connection…'}</p>:<><small>{config.provider} · {config.model}. Sends summary metrics and your question; map coordinates and building records are excluded.</small><form onSubmit={ask}><label>Your question<textarea maxLength={1500} required value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Why did it spread this way? What does the smoke show?"/></label><button className="secondary-button" disabled={busy||!question.trim()}>{busy?'Explaining…':'Explain this run'}</button></form></>}{error&&<p role="alert">{error}</p>}{answer&&<div className="sage-explanation-answer" aria-live="polite">{answer}</div>}</details>;
}
