'use client';
import {useEffect,useMemo,useState} from 'react';
import type {FeatureCollection,Polygon} from 'geojson';
import type {RunRequest,RunResult,RunState} from '@/lib/sage/types';
import {compareRuns,compoundExposure,emptyOverlay,perimeterFit,sensitivity,validateDependencies,validatePolygon} from '@/lib/sage/investigation';
import type {ThermalTrack} from '@/lib/sage/thermal';
import './sage-investigation.css';
import SageExplanation from './sage-explanation';
type View='Changes'|'What if'|'Correct'|'Observe'|'Exposure'|'Thermal';
const viewGuide:Record<View,{label:string;purpose:string;example:string}>={
 'Changes':{label:'Compare runs',purpose:'See what changed between two simulations at the same place.',example:'Try stronger wind, then compare how much farther the fire travels.'},
 'What if':{label:'Try a scenario',purpose:'Change an assumption and rerun the same geography and weather.',example:'What if the wind turns 45° after 30 minutes?'},
 'Correct':{label:'Update perimeter',purpose:'Supply a measured fire boundary and restart the forecast from that observation.',example:'Use a surveyed GeoJSON perimeter with its observation time and source.'},
 'Observe':{label:'Where to observe',purpose:'Find where the simulations disagree, and where another measurement could help.',example:'If wind changes the outcome most, a local wind reading is useful. This is not safe access guidance.'},
 'Exposure':{label:'Infrastructure exposure',purpose:'Check whether mapped roads, power or water assets share projected fire exposure.',example:'Import verified assets to explore whether services in the same settlement overlap the fire.'},
 'Thermal':{label:'Thermal history',purpose:'Review repeated satellite heat detections near this location.',example:'Repeated heat can have several causes. It does not confirm a wildfire or an industrial source.'},
};
type Saved={id:string;state:string;createdAt:string;request:RunRequest;stats?:RunResult['stats']};
const stamp=(v:string)=>new Date(v).toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
const signed=(n:number)=>`${n>0?'+':''}${n.toFixed(1)}`;
function download(name:string,value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/geo+json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function readGeo(file:File){if(file.size>64000)throw Error('Use a GeoJSON file smaller than 64 KB');const data=JSON.parse(await file.text());return data;}
export default function SageInvestigation({result,minute,location,active,onRun,onOpen,onOverlay,onInspect,onSetup}:{onSetup:()=>void;result?:RunResult;minute:number;location:{lat:number;lon:number};active:boolean;onRun:(request:RunRequest)=>void;onOpen:(id:string)=>void;onOverlay:(data:FeatureCollection)=>void;onInspect:(id:string)=>void}){
 const [view,setView]=useState<View>('Changes'),[saved,setSaved]=useState<Saved[]>([]),[baseline,setBaseline]=useState<RunResult>(),[error,setError]=useState('');
 const [wind,setWind]=useState(0),[factor,setFactor]=useState(1),[shift,setShift]=useState(0),[moisture,setMoisture]=useState(7),[east,setEast]=useState(0),[north,setNorth]=useState(0),[fuelBreak,setFuelBreak]=useState<Polygon>();
 const [perimeter,setPerimeter]=useState<Polygon>(),[observedAt,setObservedAt]=useState(''),[source,setSource]=useState('');
 const [assets,setAssets]=useState<ReturnType<typeof validateDependencies>>(),[tracks,setTracks]=useState<ThermalTrack[]>([]),[loading,setLoading]=useState(false),[thermalTime,setThermalTime]=useState(''),[coverage,setCoverage]=useState('');
 useEffect(()=>{fetch('/api/sage/runs',{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('Run history unavailable');return r.json();}).then(setSaved).catch(e=>setError(e.message));},[result?.id]);
 useEffect(()=>{if(result){setMoisture(result.request.deadMoisturePct);setWind(result.request.experiment?.windOffset??0);setFactor(result.request.experiment?.windFactor??1);setShift(result.request.experiment?.windShiftMinutes??0);setEast(result.request.experiment?.ignitionOffset[0]??0);setNorth(result.request.experiment?.ignitionOffset[1]??0);setFuelBreak(result.request.experiment?.fuelBreak);setPerimeter(undefined);setObservedAt('');setSource('');}setError('');},[result?.id]);
 useEffect(()=>{if(result?.request.experiment?.parentId&&!baseline)void chooseBaseline(result.request.experiment.parentId);},[result?.id]);
 useEffect(()=>{setTracks([]);setThermalTime('');setCoverage('');},[location.lat,location.lon]);
 const differences=useMemo(()=>{if(!result||!baseline||result.id===baseline.id)return null;try{const sharedMinute=Math.min(minute,(Date.parse(baseline.forecastOrigin)+baseline.request.horizonMinutes*60000-Date.parse(result.forecastOrigin))/60000);return {data:compareRuns(baseline,result,sharedMinute),sharedMinute};}catch(e){return {error:e instanceof Error?e.message:'Unable to compare'};}},[result,baseline,minute]);
 const sensitivityData=useMemo(()=>result?sensitivity(result):null,[result]);
 const exposure=useMemo(()=>result&&assets?compoundExposure(result,assets,minute):null,[result,assets,minute]);
 const fit=useMemo(()=>{if(!result||!perimeter||!observedAt)return null;try{return {data:perimeterFit(result,perimeter,new Date(observedAt).toISOString())};}catch(e){return {error:e instanceof Error?e.message:'Invalid perimeter'};}},[result,perimeter,observedAt]);
 useEffect(()=>{
  let overlay:FeatureCollection=emptyOverlay();
  if(view==='Changes'&&differences?.data)overlay=differences.data.overlay;
  if(view==='Observe'&&sensitivityData)overlay=sensitivityData.overlay;
  if(view==='Exposure'&&exposure)overlay=exposure.overlay;
  if(view==='Correct'&&perimeter)overlay={type:'FeatureCollection',features:[{type:'Feature',geometry:perimeter,properties:{color:'#74d2ca',label:source||'Imported perimeter'}}]};
  if(view==='What if'&&fuelBreak)overlay={type:'FeatureCollection',features:[{type:'Feature',geometry:fuelBreak,properties:{color:'#74d2ca',label:'Hypothetical fuel removal'}}]};
  if(view==='Thermal')overlay={type:'FeatureCollection',features:tracks.map(t=>({type:'Feature',geometry:{type:'Point',coordinates:t.position},properties:{color:t.priority==='review'?'#ff7958':'#e6bd6c',label:`${t.passes} passes · ${t.priority}`}}))};
  onOverlay(overlay);return()=>onOverlay(emptyOverlay());
 },[view,differences,sensitivityData,exposure,perimeter,fuelBreak,source,tracks,onOverlay]);
 async function chooseBaseline(id:string){setError('');if(!id){setBaseline(undefined);return;}try{const r=await fetch(`/api/sage/runs/${id}`);if(!r.ok)throw Error('Saved baseline unavailable');const data:RunState=await r.json();if(!data.result)throw Error('Baseline is not complete');setBaseline(data.result);}catch(e){setError((e as Error).message);}}
 async function upload(file:File|undefined,kind:'perimeter'|'fuel'|'assets'){if(!file)return;setError('');try{const raw=await readGeo(file);if(kind==='assets')setAssets(validateDependencies(raw));else{const polygon=validatePolygon(raw.type==='Feature'?raw.geometry:raw);if(kind==='fuel')setFuelBreak(polygon);else setPerimeter(polygon);}}catch(e){setError((e as Error).message);}}
 function branch(correct=false){if(!result)return;setBaseline(result);setError('');const previous=result.request.experiment;onRun({...result.request,deadMoisturePct:correct?result.request.deadMoisturePct:moisture,experiment:{parentId:result.id,windOffset:correct?previous?.windOffset??0:wind,windFactor:correct?previous?.windFactor??1:factor,windShiftMinutes:correct?previous?.windShiftMinutes??0:shift,ignitionOffset:correct?previous?.ignitionOffset??[0,0]:[east,north],fuelBreak:correct?previous?.fuelBreak:fuelBreak,observation:correct&&perimeter?{geometry:perimeter,observedAt:new Date(observedAt).toISOString(),source}:previous?.observation}});setView('Changes');}
 async function refreshThermal(){setLoading(true);setError('');try{const r=await fetch(`/api/sage/investigation?lat=${location.lat}&lon=${location.lon}`,{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error);setTracks(data.tracks);setThermalTime(data.generatedAt);setCoverage(data.sources.filter((s:{source:string})=>/satellite|firms|deepfire|viirs/i.test(s.source)).map((s:{source:string;status:string})=>`${s.source}: ${s.status}`).join(' · ')||'Coverage unknown');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 const compatible=saved.filter(s=>s.state==='completed'&&s.id!==result?.id&&(!result||(s.request.lat===result.request.lat&&s.request.lon===result.request.lon)));
 return <section className="investigation" aria-label="GingerO2 investigation"><nav className="investigation-tabs" aria-label="Investigation views">{(['Changes','What if','Correct','Observe','Exposure','Thermal'] as View[]).map(v=><button key={v} aria-pressed={view===v} onClick={()=>{setView(v);setError('');}}>{viewGuide[v].label}</button>)}</nav><div className="investigation-body">{result&&<SageExplanation runId={result.id}/>}<header className="investigation-guide"><span className="investigation-eyebrow">{view==='Thermal'?'SATELLITE EVIDENCE':'SCENARIO WORKSPACE'}</span><h2>{viewGuide[view].label}</h2><p>{viewGuide[view].purpose}</p><details><summary>How to use this</summary><p>{viewGuide[view].example}</p></details></header>
 {error&&<p role="alert" className="investigation-error">{error}</p>}
 {!result&&view!=='Thermal'?<div className="investigation-empty"><h3>Start with your first simulation</h3><p>Choose an origin and run GingerO2. Your results will appear here.</p><button className="primary-button" onClick={onSetup}>Set up a simulation ↗</button><label>Open a saved run<select defaultValue="" disabled={active} onChange={e=>{if(e.target.value)onOpen(e.target.value);}}><option value="">Select a forecast</option>{saved.filter(s=>s.state==='completed').map(s=><option key={s.id} value={s.id}>{stamp(s.createdAt)} · {s.request.lat.toFixed(3)}, {s.request.lon.toFixed(3)}</option>)}</select></label></div>:<>
 {result&&!result.inputSnapshot&&view!=='Thermal'&&<button className="secondary-button" disabled={active} onClick={()=>onRun({...result.request,experiment:undefined})}>Refresh baseline for branching ↗</button>}
 {view==='Changes'&&<><label>Compare against<select disabled={!compatible.length} value={baseline?.id??''} onChange={e=>void chooseBaseline(e.target.value)}><option value="">Select baseline</option>{compatible.map(s=><option key={s.id} value={s.id}>{stamp(s.createdAt)} · {s.stats?.burnedHa.toFixed(1)} ha</option>)}</select></label>{differences?.error&&<p role="status">{differences.error}</p>}{differences?.data?<><small>Shared forecast · +{differences.sharedMinute?.toFixed(0)}m from current origin</small><div className="investigation-metrics"><div><b>{signed(differences.data.addedHa)}</b><span>new ha</span></div><div><b>−{differences.data.removedHa.toFixed(1)}</b><span>retracted ha</span></div><div><b>{differences.data.newlyExposed.length}</b><span>new buildings</span></div></div>{result?.request.experiment?.parentId===baseline?.id&&!!result?.drivers?.length&&<><h3>Isolated effects · full horizon</h3>{result.drivers.map(d=><div className="investigation-row" key={d.name}><span>{d.name}</span><strong>{signed(d.areaDeltaHa)} ha · {d.buildingDelta>0?'+':''}{d.buildingDelta} buildings</strong></div>)}<small>One change at a time. Effects do not add up.</small></>}<h3>Changed inputs</h3>{differences.data.changed.length?differences.data.changed.map(c=><p className="investigation-row" key={c}>{c}</p>):<p>Same recorded inputs.</p>}<small>{differences.data.changed.length>1?'Multiple changes · effects not isolated':'Controlled branch only when geography and weather are held fixed'}</small><div className="investigation-key"><span>● Coral · added</span><span>● Teal · retracted</span></div>{differences.data.newlyExposed.slice(0,8).map(b=><button className="investigation-row" key={b.id} onClick={()=>onInspect(b.id)}>{b.name}<strong>+{b.arrivalMin}m ↗</strong></button>)}</>:<div className="investigation-next"><h3>{compatible.length?'Choose a run to compare':'Your first run is the starting point'}</h3><p>{compatible.length?'Select a saved run above, or change one assumption to make a controlled comparison.':'Create a second version with a different wind or moisture setting. GingerO2 will compare it with this run automatically.'}</p><button className="primary-button" disabled={active} onClick={()=>setView('What if')}>Try a different scenario ↗</button></div>}</>}
 {view==='What if'&&result&&<><div className="investigation-example"><p>Try it: turn the wind <b>45°</b> after <b>30 minutes</b>.</p><button className="secondary-button" onClick={()=>{setWind(45);setShift(30);}}>Use this example</button></div><div className="investigation-pair"><label>Turn wind · °<input type="number" min={-180} max={180} value={wind} onChange={e=>setWind(Number(e.target.value))}/></label><label>Wind speed ×<input type="number" min={0} max={3} step={.1} value={factor} onChange={e=>setFactor(Number(e.target.value))}/></label><label>Change starts<select value={shift} onChange={e=>setShift(Number(e.target.value))}>{[0,30,60,90,120,150,180,210,240].map(n=><option value={n} key={n}>+{n} min</option>)}</select></label><label>Dead moisture · %<input type="number" min={1} max={60} step={.5} value={moisture} onChange={e=>setMoisture(Number(e.target.value))}/></label><label>Ignition east · m<input disabled={!!result.request.experiment?.observation} type="number" min={-750} max={750} step={25} value={east} onChange={e=>setEast(Number(e.target.value))}/></label><label>Ignition north · m<input disabled={!!result.request.experiment?.observation} type="number" min={-750} max={750} step={25} value={north} onChange={e=>setNorth(Number(e.target.value))}/></label></div><p className="investigation-control-help">1× keeps the forecast wind speed; 2× doubles it. Positive degrees turn it clockwise. The change starts at the selected minute.</p><label className="investigation-upload">{fuelBreak?'Fuel removal loaded':'Import fuel-removal polygon'}<input type="file" accept=".json,.geojson" onChange={e=>void upload(e.target.files?.[0],'fuel')}/></label>{fuelBreak&&<button onClick={()=>setFuelBreak(undefined)}>Remove polygon</button>}<small>Fixed geography & weather. Fuel removal models surface fuel only.</small><button className="primary-button" disabled={active||!result.inputSnapshot||!Number.isFinite(wind)||wind<-180||wind>180||!Number.isFinite(factor)||factor<0||factor>3||moisture<1||moisture>60||Math.abs(east)>750||Math.abs(north)>750} onClick={()=>branch()}>Run this scenario ↗</button></>}
 {view==='Correct'&&result&&<><label className="investigation-upload">{perimeter?'Perimeter loaded':'Import observed perimeter'}<input type="file" accept=".json,.geojson" onChange={e=>void upload(e.target.files?.[0],'perimeter')}/></label><label>Observed at · local time<input type="datetime-local" value={observedAt} onChange={e=>setObservedAt(e.target.value)}/></label><label>Source / reference<input maxLength={240} placeholder="Survey or incident reference" value={source} onChange={e=>setSource(e.target.value)}/></label>{fit?.error&&<p role="alert">{fit.error}</p>}{fit?.data&&<div className="investigation-metrics"><div><b>{Math.round(fit.data.overlap*100)}%</b><span>overlap</span></div><div><b>{fit.data.missedHa.toFixed(1)}</b><span>missed ha</span></div><div><b>{fit.data.extraHa.toFixed(1)}</b><span>extra ha</span></div></div>}<small>Operator-supplied extent. Original forecast stays saved.</small><button className="primary-button" disabled={active||!result.inputSnapshot||!fit?.data||source.trim().length<3} onClick={()=>branch(true)}>Run corrected forecast ↗</button></>}
 {view==='Observe'&&sensitivityData&&<><p>{sensitivityData.members[0]?.score>0?`Measure ${sensitivityData.members[0].name.startsWith('Wind')?'local wind':'fuel moisture'} first.`:'No building sensitivity resolved.'}</p>{sensitivityData.members.map(m=><div className="investigation-sensitivity" key={m.name}><span>{m.name}</span><meter min={0} max={Math.max(1,...sensitivityData.members.map(x=>x.score))} value={m.score}/><small>{m.changed} buildings differ · up to {m.maxShift}m</small></div>)}<h3>Front-check locations</h3>{sensitivityData.targets.map((t,i)=><div className="investigation-row" key={i}><span>{t.position[1].toFixed(5)}, {t.position[0].toFixed(5)}</span><strong>{t.disagreement?`${t.disagreement}/${result?.members.length} not reached`:`${t.spread.toFixed(0)}m spread`}</strong></div>)}{!sensitivityData.targets.length&&<p>No spatial disagreement in this run.</p>}<small>Isolated input changes. Purple areas are candidates for a front observation, not field access guidance.</small><div className="investigation-key"><span>● Purple · reach differs</span><span>● Amber · timing differs</span></div></>}
 {view==='Exposure'&&result&&<><label className="investigation-upload">{assets?`${assets.features.length} assets loaded`:'Import infrastructure GeoJSON'}<input type="file" accept=".json,.geojson" onChange={e=>void upload(e.target.files?.[0],'assets')}/></label><button className="secondary-button" onClick={()=>download('ginger-dependencies-template.geojson',{type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Point',coordinates:result.center},properties:{name:'Replace with verified asset',group:'Settlement name',kind:'power',source:'Replace with source',verifiedAt:new Date().toISOString()}}]})}>Download template</button>{exposure?.groups.map(g=><article className="investigation-group" key={g.name}><h3>{g.name}<span>{g.exposedKinds.length>=2?'Compound exposure':`${g.exposedKinds.length} type exposed`}</span></h3>{g.assets.map((a,i)=><div className="investigation-row" key={i}><span>{a.name}<small>{a.kind} · {a.source} · {stamp(a.verifiedAt)}</small></span><strong>{a.exposed?'Exposed':a.partial?'Partial domain':'Not reached'}</strong></div>)}</article>)}<small>Same-group co-exposure. Service failure and route safety are not inferred.</small></>}
 {view==='Thermal'&&<><div className="investigation-title"><h3>Recent detections</h3><button className="secondary-button" disabled={loading} onClick={()=>void refreshThermal()}>{loading?'Loading…':'Refresh'}</button></div><small>10 km · 500 m clusters · up to 30 days collected</small>{thermalTime&&<p className="investigation-source">{stamp(thermalTime)}<br/>{coverage}</p>}{tracks.map(t=><article className="investigation-group" key={t.id}><h3>{t.position[1].toFixed(3)}, {t.position[0].toFixed(3)}<span>{t.priority}</span></h3><div className="investigation-metrics"><div><b>{t.passes}</b><span>passes</span></div><div><b>{t.days}</b><span>days</span></div><div><b>{t.peakMw?.toFixed(1)??'—'}</b><span>peak MW</span></div></div><div className="investigation-spark" aria-label="Peak thermal power by pass">{t.history.map(h=><i key={h.time} title={`${stamp(h.time)} · ${h.mw??'Unknown'} MW`} style={{height:`${Math.max(4,(h.mw??0)/Math.max(1,t.peakMw??1)*36)}px`}}/>)}</div><small>{t.reasons.join(' · ')}</small></article>)}{!tracks.length&&<p>{thermalTime?'No retained detections here. Coverage may be incomplete.':'Refresh to track satellite observations.'}</p>}<details><summary>Review rules</summary><p>Recent detection plus rising peak FRP or dry, windy weather raises review priority. Recurrence never confirms an industrial source. No detections is not an all-clear.</p></details></>}
 </>}
 </div></section>;
}
