'use client';
import {useEffect,useRef,useState} from 'react';
import type {ForestSceneStatus} from './sage-forest-scene';
import type {ForestStatus} from '@/lib/forest/types';
const PREPARED_DEMO='/sage?engine=terrain-wind&run=c41b7bf820e449178dc73fdd3dd3caa1&lat=41.43&lon=2.094';
export default function SageForestAvailability({center,status}:{center:[number,number];status:ForestSceneStatus|null}){
 const [tiles,setTiles]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const controller=useRef<AbortController|null>(null);const location=center.join(',');
 useEffect(()=>{controller.current?.abort();setTiles([]);setBusy(false);setMessage('');return()=>controller.current?.abort();},[location]);
 useEffect(()=>{if(!tiles.length)return;const abort=new AbortController();let timer:ReturnType<typeof setTimeout>;
  const check=async()=>{try{const response=await fetch('/api/forest/status',{signal:abort.signal,cache:'no-store'});if(!response.ok)throw Error('Could not check preparation.');const data=await response.json() as ForestStatus;const selected=tiles.map(id=>data.tiles.find(tile=>tile.id===id));const done=selected.filter(tile=>tile?.state==='completed').length;const failed=selected.find(tile=>tile&&['failed','interrupted'].includes(tile.state));window.dispatchEvent(new Event('ginger-forest-refresh'));if(done===tiles.length){setTiles([]);setMessage('Trees prepared. Loading the measured crowns here.');return;}if(failed){setTiles([]);setMessage(failed.error||'Tree preparation stopped. You can retry.');return;}setMessage(`Preparing trees here: ${done} of ${tiles.length} tiles ready. This can take several minutes.`);}catch(error){if(abort.signal.aborted)return;setMessage((error as Error).message);}if(!abort.signal.aborted)timer=setTimeout(check,10000);};void check();return()=>{abort.abort();clearTimeout(timer);};
 },[tiles]);
 async function prepare(){controller.current?.abort();const abort=new AbortController();controller.current=abort;setBusy(true);setMessage('Requesting the LiDAR tiles around this origin…');try{const response=await fetch('/api/forest/process',{method:'POST',signal:abort.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({lat:center[1],lon:center[0],radiusM:500})});const data=await response.json();if(!response.ok)throw Error(data.detail||data.error||'Tree preparation is unavailable.');setTiles(data.tiles);setMessage('Preparing this 1 km study area. Trees will appear as tiles finish.');}catch(error){if(!abort.signal.aborted)setMessage((error as Error).message);}finally{if(!abort.signal.aborted)setBusy(false);}}
 if(!tiles.length&&!message&&(status?.count||status?.state==='loading'||status?.state==='zoom-in'||!status))return null;
 return <div className="sage-forest-availability" style={{padding:14,borderRadius:12,background:"rgba(12,25,20,.94)",border:"1px solid #40513d",color:"#e5eadc",fontSize:12}}><p>{status?.count?`${status.count.toLocaleString()} crowns in this view. Unprepared tiles can still leave gaps.`:status?.state==='unavailable'?'Tree coverage could not be loaded. Retry preparation or open the prepared scene.':'No prepared crowns in this view. Prepare this area, or explore an already prepared scene.'}</p><button className="ginger-setup-toggle" disabled={busy||tiles.length>0} onClick={()=>void prepare()}>{busy||tiles.length?'Preparing trees…':'Prepare trees here'}</button>{message&&<p role="status">{message}</p>}<p><a href={PREPARED_DEMO}>Open prepared 3D demo ↗</a></p></div>;
}
