'use client';
import {useState} from 'react';
import {EvidenceBadge} from './evidence';
import type {MonitorSnapshot} from '@/lib/monitor';
export type WatchAreaView={id:string;name:string;lat:number;lon:number;radiusM:number;createdAt:string};
export default function WatchAreaPanel({areas,monitor,location,onSelect,onChange}:{areas:WatchAreaView[];monitor:MonitorSnapshot|null;location:{name:string;lat:number;lon:number};onSelect:(area:WatchAreaView)=>void;onChange:()=>Promise<void>}){
 const [name,setName]=useState(''),[radius,setRadius]=useState('1500'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function add(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/watch-areas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,lat:location.lat,lon:location.lon,radiusM:Number(radius)})});const j=await r.json();if(!r.ok)throw Error(j.error||'Could not save area');setName('');await onChange();}catch(e){setError(e instanceof Error?e.message:'Could not save area');}finally{setBusy(false);}}
 async function remove(id:string){setBusy(true);setError('');try{const r=await fetch(`/api/watch-areas?id=${encodeURIComponent(id)}`,{method:'DELETE'});const j=await r.json();if(!r.ok)throw Error(j.error||'Could not remove area');await onChange();}catch(e){setError(e instanceof Error?e.message:'Could not remove area');}finally{setBusy(false);}}
 return <div className="upgrade-panel"><div className="upgrade-intro"><span className="eyebrow">YOUR MONITORING NETWORK</span><h3>A place to keep watching.</h3><p>Saved on this backend. Weather and satellite checks run every ten minutes while the server is running.</p></div><div className="watch-grid">{areas.map(a=>{const z=monitor?.zones.find(z=>z.id===a.id);return <article key={a.id} className="watch-card"><button className="watch-select" onClick={()=>onSelect(a)}><div><strong>{a.name}</strong><span className={'badge '+(z?.state==='escalating'?'critical':z?.state==='review'?'high':'watch')}>{z?.state||'scan pending'}</span></div><p>{a.lat.toFixed(3)}°, {a.lon.toFixed(3)}° · {(a.radiusM/1000).toFixed(1)} km radius</p><EvidenceBadge kind="simulated" detail="Modelled weather"/><div className="watch-numbers"><span><b>{z?.temperature??'—'}</b> °C</span><span><b>{z?.humidity??'—'}</b> % RH</span><span><b>{z?.windKmh??'—'}</b> km/h</span></div><EvidenceBadge kind="derived" detail="Review status"/><p>{z?.reasons[0]||'Awaiting the next regional scan.'}</p><span className="watch-link">Inspect landscape ↗</span></button><button className="remove-watch" disabled={busy} aria-label={`Remove ${a.name} from watch areas`} onClick={()=>void remove(a.id)}>Remove from watch</button></article>;})}</div><form className="upgrade-form" onSubmit={add}><h3>Watch the selected location</h3><p>{location.name} · {location.lat.toFixed(5)}°, {location.lon.toFixed(5)}°. Select another point on the map to change it.</p><div className="upgrade-fields"><label>Area name<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Municipality or infrastructure corridor"/></label><label>Watch radius (metres)<input required type="number" min={500} max={10000} step={100} value={radius} onChange={e=>setRadius(e.target.value)}/></label></div><button className="primary-button" disabled={busy||areas.length>=20}>{busy?'Saving…':'Save watch area'}</button>{error&&<p role="alert" className="red-text">{error}</p>}</form></div>;
}
