import assert from 'node:assert/strict';
import {clipPuffToDomain,advectPuff,smokeIllustration,windAt,SMOKE_ASSUMPTIONS} from '../src/lib/sage/smoke';
import {cellPolygon,toLocal} from '../src/lib/sage/geometry';
import type {RunResult,WeatherFrame} from '../src/lib/sage/types';
const weather=(minute:number,from:number,speed=6):WeatherFrame=>({time:new Date(Date.parse('2026-01-01T00:00:00Z')+minute*60000).toISOString(),windFromDegrees:from,windKmh:speed,temperatureC:25,humidityPct:30,directNormalWm2:0,diffuseWm2:0,precipitationMm:0});
const run={forecastOrigin:'2026-01-01T00:00:00Z',center:[0,0],size:100,cellM:25,request:{horizonMinutes:120,ignitionRadiusM:0,lon:0,lat:0},weather:[weather(0,270),weather(60,180),weather(120,180)],cells:{type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Polygon',coordinates:[[[-.0001,-.0001],[.0001,-.0001],[.0001,.0001],[-.0001,.0001],[-.0001,-.0001]]]},properties:{arrivalCentral:5}}]},buildings:[]} as unknown as RunResult;
assert.equal(windAt(run,0)?.toDegrees,90,'meteorological west wind blows east');
const east=advectPuff(run,[0,0],0,10)!;assert.ok(Math.abs(east[0]-1000)<1e-8&&Math.abs(east[1])<1e-8);
const turn=advectPuff(run,[0,0],59,61)!;assert.ok(Math.abs(turn[0]-100)<1e-8&&Math.abs(turn[1]-100)<1e-8,'forecast change splits transport');
const shifted={...run,request:{...run.request,experiment:{parentId:'x',windFactor:2,windOffset:90,windShiftMinutes:30,ignitionOffset:[0,0] as [number,number]}}};
assert.equal(windAt(shifted,29)?.toDegrees,90);assert.equal(windAt(shifted,30)?.toDegrees,180);
const experimentTurn=advectPuff(shifted,[0,0],29.5,30.5)!;assert.ok(Math.abs(experimentTurn[0]-50)<1e-8&&Math.abs(experimentTurn[1]+100)<1e-8);
assert.equal(smokeIllustration(run,4).plumes.features.length,0,'no release before modeled arrival');
assert.ok(smokeIllustration(run,6).plumes.features.length>0);
assert.equal(smokeIllustration(run,46).plumes.features.length,0,'old burned cells do not emit forever');
const calm={...run,weather:[weather(0,270,0),weather(60,0,0),weather(120,0,0)]};
assert.deepEqual(advectPuff(calm,[100,200],0,10),[100,200]);
const puffs=smokeIllustration(calm,10).plumes.features;assert.ok(puffs[0].properties!.radiusM>puffs[puffs.length-1].properties!.radiusM,'older calm puffs spread wider');
assert.equal(smokeIllustration(run,-10).minute,0);assert.equal(smokeIllustration(run,1000).minute,120);
assert.deepEqual(smokeIllustration(calm,12),smokeIllustration(calm,12),'deterministic');
for(const f of smokeIllustration(run,10).plumes.features){assert.ok(f.properties!.opacity>=0);assert.ok(!('concentration' in f.properties!));for(const [lon,lat] of f.geometry.coordinates[0]){assert.ok(Number.isFinite(lon)&&Number.isFinite(lat));const [x,y]=toLocal([lon,lat],run.center);assert.ok(Math.abs(x)<=1250.0001&&Math.abs(y)<=1250.0001);}}
assert.equal(advectPuff({...run,weather:[]},[0,0],0,1),null,'missing weather does not fabricate drift');
const many={...calm,cells:{...calm.cells,features:Array.from({length:1000},()=>calm.cells.features[0])}};
assert.ok(smokeIllustration(many,10).sampledSources<=SMOKE_ASSUMPTIONS.maxSources);
const structures={...calm,cells:{type:'FeatureCollection' as const,features:[]},buildings:[{center:[0,0],structuralIgnitionByMember:[20]}]} as unknown as RunResult;
assert.equal(smokeIllustration(structures,19).plumes.features.length,0);assert.ok(smokeIllustration(structures,40).plumes.features.length>0);assert.equal(smokeIllustration(structures,80).plumes.features.length,0);
assert.equal(smokeIllustration(run,10,false).plumes.features.length,0,'disabled layer skips transport work');
assert.equal(smokeIllustration(calm,10).fireHeadingDegrees,null,'initial symmetric source does not imply fire direction');
assert.deepEqual(clipPuffToDomain([108,108],10,100),[],'corner bounding-box overlap does not imply circle intersection');
assert.deepEqual(clipPuffToDomain([110,0],10,100),[],'tangent puff creates no degenerate line polygon');
const clipped=clipPuffToDomain([105,105],10,100);assert.ok(clipped.length>=4);assert.deepEqual(clipped[0],clipped[clipped.length-1]);assert.ok(clipped.every(([x,y])=>Math.abs(x)<=100.000001&&Math.abs(y)<=100.000001));
const reached=(x:number,y:number,arrival:number)=>({type:'Feature' as const,geometry:cellPolygon(x,y,5,run.center),properties:{arrivalCentral:arrival}});
const turning={...calm,cells:{type:'FeatureCollection' as const,features:[reached(900,0,2),reached(1000,-10,12),reached(1000,0,12),reached(1000,10,12),reached(990,100,18),reached(1000,100,18),reached(1010,100,18)]}};
assert.ok(Math.abs(smokeIllustration(turning,20,false).fireHeadingDegrees!)<1e-6,'recent centroid shift is north despite old eastward displacement');
assert.equal(smokeIllustration({...turning,cells:{...turning.cells,features:turning.cells.features.slice(-3)}},20,false).fireHeadingDegrees,null,'one time window cannot establish movement');
const symmetric={...calm,cells:{type:'FeatureCollection' as const,features:[reached(-100,0,12),reached(100,0,12),reached(0,0,12),reached(-200,0,18),reached(200,0,18),reached(0,0,18)]}};
assert.equal(smokeIllustration(symmetric,20,false).fireHeadingDegrees,null,'symmetric expansion has no centroid motion');
console.log('GingerO2 smoke: direction, changing weather, experiment timing, calm diffusion, finite residence, structural timing, bounds and deterministic sampling passed.');

const partialHour={...run,weather:[{...weather(0,270,1.8),validForMinutes:30},weather(0,180,5.7)]};
assert.equal(windAt(partialHour,29)?.speedKmh,1.8);
assert.equal(windAt(partialHour,30)?.speedKmh,5.7,"expired station interval yields to captured forecast");
