import assert from 'node:assert/strict';
import {sensorPasses,perimeterFrame,parseLabQuery,parseSpreadInput} from '../src/lib/satellite-lab';
import {DeepfireProvider} from '../src/lib/providers/deepfire';
import {parseScene,publicAsset} from '../src/lib/providers/sentinel';
import {parseFirmsCSV} from '../src/lib/providers/firms';
import type {FeatureCollection} from 'geojson';
const obs=(source:string,time:string,frp:unknown,extra={})=>({type:'Feature' as const,geometry:{type:'Point' as const,coordinates:[1,41]},properties:{source,observed_at:time,fire_radiative_power:frp,...extra}});
const time='2026-09-01T10:00:00Z';
const fc=(features:FeatureCollection['features']):FeatureCollection=>({type:'FeatureCollection',features});
const passes=sensorPasses(fc([obs('A',time,4),obs('A',time,6),obs('B',time,20),obs('A','2026-09-01T11:00:00Z',null,{bright_ti4:320,bright_ti5:290})]));
assert.equal(passes.length,3);assert.equal(passes[0].frpMw,10);assert.equal(passes[1].frpMw,20);assert.equal(passes[2].frpMw,null);assert.equal(passes[2].thermalContrastK,30);
const a={...obs('A',time,1),properties:{cluster_id:'a',computed_at:time}},b={...a,properties:{cluster_id:'a',computed_at:'2026-09-01T11:00:00Z'}};
assert.equal(perimeterFrame(fc([b,a]),Date.parse(time)).features[0],a);assert.equal(perimeterFrame(fc([a,b]),Date.parse('2026-09-01T12:00:00Z')).features.length,1);
for(const q of ['lat=&lon=1','lat=NaN&lon=1','lat=90&lon=1','lat=41&lon=1&days=8'])assert.throws(()=>parseLabQuery(new URLSearchParams(q)));
assert.throws(()=>parseSpreadInput({latitude:41,longitude:1,durationHours:6,model:'bad',ensembleMembers:1}));
assert.equal(parseSpreadInput({latitude:41,longitude:1,durationHours:6,model:'elmfire',ensembleMembers:1}).durationHours,6);
assert.equal(publicAsset('file:///etc/passwd'),null);assert.equal(publicAsset('https://evil.test/B04.tif'),null);assert.equal(publicAsset('https://sentinel-cogs.s3.us-west-2.amazonaws.com@evil.test/a'),null);
assert.throws(()=>parseScene({}));
const asset={href:'https://e84-earth-search-sentinel-data.s3.us-west-2.amazonaws.com/example/B04.tif','raster:bands':[{scale:.0001,offset:-.1}]};
const scene=parseScene({id:'S2A_T31TCG_20260915T103959_L2A',properties:{datetime:time},assets:{red:asset}});
assert.equal(scene.assets.red.scale,.0001);assert.equal(scene.assets.red.offset,-.1);
const rows=parseFirmsCSV('latitude,longitude,acq_date,acq_time,frp,confidence,bright_ti4,bright_ti5,scan,track,daynight\n41,1,2026-09-01,1000,3,n,320,290,0.4,0.5,D');assert.equal(rows[0].raw?.bright_ti4,'320');
async function main(){const original=global.fetch,token=process.env.DEEPFIRE_TOKEN;process.env.DEEPFIRE_TOKEN='test-only';let posts=0;
 try{global.fetch=async(url,init)=>{const u=new URL(String(url));if(init?.method==='POST'){posts++;return new Response('',{status:503});}const filter=u.searchParams.get('filter')!;assert.match(filter,/observed_at >= TIMESTAMP/);assert.doesNotMatch(filter,/active = true/);return Response.json(fc([]));};
 const p=new DeepfireProvider();await p.history('hotspots',[1,41,2,42],time,'2026-09-02T10:00:00Z');
 await assert.rejects(()=>p.history('hotspots',[1,41,2,42],time,'2026-09-10T10:00:00Z'));
 await assert.rejects(()=>p.createSpread({latitude:41,longitude:1,durationHours:6,model:'elmfire',ensembleMembers:1}));assert.equal(posts,1,'Paid simulation POST must never be retried');
 console.log('PASS sensor separation, missing FRP, thermal contrast, temporal frames, query bounds, asset allowlist, preserved raw fields, bounded archive and no mutation replay');
 }finally{global.fetch=original;if(token===undefined)delete process.env.DEEPFIRE_TOKEN;else process.env.DEEPFIRE_TOKEN=token;}}
void main();
