import assert from 'node:assert/strict';
import {area,cellPolygon,contains,intersectsCell,localPolygons,toLocal,toLonLat} from '../src/lib/sage/geometry';
import {createBehaviorModel,directionalRate,equilibriumMoisture,irradiance,shadowed,solarMoisture,sunPosition} from '../src/lib/sage/physics';
import {fuelForCategory,IgnitionError,simulateLandscape} from '../src/lib/sage/engine';
import {normalizeBuildings,parseCollection,parseSimulationWeather,terrariumHeight} from '../src/lib/sage/landscape';
import {validateRunRequest} from '../src/lib/sage/validation';
import type {Landscape,RunRequest} from '../src/lib/sage/types';
let count=0;function test(name:string,fn:()=>void){fn();console.log('PASS',name);count++;}
const request:RunRequest={lat:41.73,lon:1.83,horizonMinutes:60,ignitionRadiusM:25,deadMoisturePct:7,liveMoisturePct:90,windAdjustment:.35,mode:'scenario',confirmation:'',solarDrying:false};
const origin='2026-09-19T12:00:00.000Z';
function fixture():Landscape{
  const center:[number,number]=[1.83,41.73];
  return {center,size:20,cellM:25,elevations:Array(400).fill(100),buildings:{type:'FeatureCollection',features:[-1,1].map((side,i)=>({type:'Feature',geometry:cellPolygon(side*100,0,10,center),properties:{id:`b${i}`,name:`Building ${i}`,heightM:12,heightSource:'test fixture',source:'test'}}))},landcover:{type:'FeatureCollection',features:[{type:'Feature',geometry:cellPolygon(0,0,250,center),properties:{categoria:'Prats i herbassars'}}]},weather:Array.from({length:6},(_,i)=>({time:new Date(Date.parse(origin)+i*3600000).toISOString(),temperatureC:30,humidityPct:20,windKmh:30,windFromDegrees:270,directNormalWm2:600,diffuseWm2:100,precipitationMm:0})),sources:[],warnings:[]};
}
test('Rothermel reference: library published fuel 10 / 10 mph / 25% slope benchmark, converted to SI',()=>{const b=createBehaviorModel()('10',5,50,16.09344,180,[0,.25]);assert.ok(Math.abs(b.headMMin-38.894889923053256*.3048)<1e-8);assert.ok(Math.abs(b.flameM-10.43340945465685*.3048)<1e-8);assert.ok(Math.abs(b.headingDegrees)<1e-6);});
test('meteorological FROM wind drives the front downwind, not toward its source',()=>{const b=createBehaviorModel()('1',7,90,10,270,[0,0]);assert.ok(Math.abs(b.headingDegrees-90)<1e-6);assert.ok(directionalRate(b,90)>directionalRate(b,270)*2);});
test('moisture increase slows spread; units never become percentages of percentages',()=>{const model=createBehaviorModel();assert.ok(model('1',15,90,10,270,[0,0]).headMMin<model('1',5,90,10,270,[0,0]).headMMin);});
test('geometry preserves courtyard holes, thin crossings, and metric footprint area',()=>{const parts:[number,number][][][]=[[[[-20,-20],[20,-20],[20,20],[-20,20],[-20,-20]],[[-5,-5],[5,-5],[5,5],[-5,5],[-5,-5]]]];assert.equal(area(parts),1500);assert.equal(contains([0,0],parts),false);assert.equal(intersectsCell(parts,0,0,2),false);assert.equal(intersectsCell(parts,0,10,2),true);const thin:[number,number][][][]=[[[[-20,-.1],[20,-.1],[20,.1],[-20,.1],[-20,-.1]]]];assert.equal(intersectsCell(thin,0,0,1),true);});
test('Terrarium RGB correctly decodes negative and fractional elevation',()=>{assert.equal(terrariumHeight(128,0,128),.5);assert.equal(terrariumHeight(127,255,0),-1);});
test('ICGC parser keeps only buildings and preserves unknown heights',()=>{const g=cellPolygon(0,0,10,[1.83,41.73]);const c={type:'FeatureCollection' as const,features:[{type:'Feature' as const,geometry:g,properties:{id:1,tipus:'edi',altura:12.5}},{type:'Feature' as const,geometry:g,properties:{id:2,tipus:'edi',altura:0}},{type:'Feature' as const,geometry:g,properties:{id:3,tipus:'ill',altura:40}}]};const b=normalizeBuildings(c);assert.equal(b.features.length,2);assert.equal(b.features[0].properties?.heightM,12.5);assert.equal(b.features[1].properties?.heightM,null);assert.throws(()=>parseCollection({...c,code:500}));assert.throws(()=>parseCollection({...c,features:[{...c.features[0],geometry:{type:'Polygon',coordinates:[[[0,0],[1,0],[1,1],[0,1]]]}}]}));});
test('Simard EMC converts Celsius to Fahrenheit in all humidity regimes',()=>{assert.ok(Math.abs(equilibriumMoisture(20,5)-1.241135)<1e-8);assert.ok(Math.abs(equilibriumMoisture(20,30)-6.02566)<1e-8);assert.ok(Math.abs(equilibriumMoisture(20,70)-12.83917)<1e-8);});
test('solar night and building shadows are physically directed',()=>{const night=sunPosition('2026-09-19T00:00Z',[1.83,41.73]);assert.ok(night.altitudeDegrees<0);assert.equal(irradiance(500,80,night,[0,0],false),0);const surface=Array(100).fill(0);surface[5*10+7]=30;assert.equal(shadowed([5,5],.1,20,90,surface,10,10),true);assert.equal(shadowed([5,5],.1,20,270,surface,10,10),false);assert.ok(solarMoisture(10,30,30,700,10,1)<solarMoisture(10,30,30,0,10,1));});
test('request validation rejects silent coercion and unconfirmed live declarations',()=>{assert.deepEqual(validateRunRequest(request),request);for(const patch of [{lat:NaN},{lon:'1.83'},{mode:'confirmed',confirmation:''},{horizonMinutes:61},{windAdjustment:0},{deadMoisturePct:null}])assert.throws(()=>validateRunRequest({...request,...patch}));});
test('land-cover classes keep unknown separate from nonburnable',()=>{assert.equal(fuelForCategory('Matollar'),6);assert.equal(fuelForCategory('Boscos densos de coníferes'),9);assert.equal(fuelForCategory('Prats i herbassars'),1);assert.equal(fuelForCategory('Aigua continental'),0);assert.equal(fuelForCategory('Sòl nu forestal'),0);assert.equal(fuelForCategory('Casc urbà'),0);assert.equal(fuelForCategory('Zones verdes'),1);assert.equal(fuelForCategory('Unrecognized category'),-1);});
let result:ReturnType<typeof simulateLandscape>;
test('ensemble uses full building footprints, deterministic arrivals and downwind ordering',()=>{result=simulateLandscape(fixture(),request,'fixture',()=>{},origin);const west=result.buildings.find(b=>b.id==='b0')!,east=result.buildings.find(b=>b.id==='b1')!;assert.ok(east.arrivalMin!==null);assert.ok((east.arrivalMin??Infinity)<(west.arrivalMin??Infinity));assert.equal(result.members.length,9);assert.equal(result.buildings.length,2);assert.equal(east.areaM2,400);assert.equal(east.arrivalByMember.length,9);const again=simulateLandscape(fixture(),request,'fixture',()=>{},origin);assert.deepEqual(again.cells,result.cells);assert.deepEqual(again.buildings,result.buildings);});
test('barriers stop propagation and unknown fuel cannot be treated as safe terrain',()=>{const f=fixture();f.landcover.features.push({type:'Feature',geometry:cellPolygon(60,0,30,f.center),properties:{categoria:'Aigua'}});const r=simulateLandscape(f,request,'barrier',()=>{},origin);assert.ok(r.cells.features.length<result.cells.features.length);const missing=fixture();missing.landcover.features=[];assert.throws(()=>simulateLandscape(missing,request,'missing',()=>{},origin),/land cover/);});
test('no burnable ignition refuses a fake forecast and partial buildings are flagged',()=>{const f=fixture();f.landcover.features[0].properties={categoria:'Aigua'};assert.throws(()=>simulateLandscape(f,request,'water',()=>{},origin),/no mapped burnable/);const p=fixture();p.buildings.features.push({type:'Feature',geometry:cellPolygon(245,0,20,p.center),properties:{id:'partial',name:'Partial',heightM:null}});const r=simulateLandscape(p,request,'partial',()=>{},origin);assert.equal(r.buildings.find(b=>b.id==='partial')?.status,'partial-coverage');assert.equal(r.buildings.find(b=>b.id==='partial')?.solarWm2,null);});
test('small ignitions and observed extents intersect fuel cells even when no centre is inside',()=>{
  const f=fixture();
  const small=simulateLandscape(f,{...request,ignitionRadiusM:1},'small',()=>{},origin);
  assert.ok(small.cells.features.some(c=>c.properties?.arrivalCentral===0));
  const observed=simulateLandscape(f,{...request,experiment:{parentId:'test',windOffset:0,windFactor:1,windShiftMinutes:0,ignitionOffset:[0,0],observation:{geometry:cellPolygon(0,0,1,f.center),observedAt:origin,source:'test'}}},'observed',()=>{},origin);
  assert.ok(observed.cells.features.some(c=>c.properties?.arrivalCentral===0));
});
test('blocked origins offer mapped vegetation without silently moving the fire or igniting buildings',()=>{
  const f=fixture();f.buildings.features.push({type:'Feature',geometry:cellPolygon(0,0,60,f.center),properties:{id:'origin-building'}});
  let recovery;
  try{simulateLandscape(f,request,'blocked',()=>{},origin);assert.fail('Must reject blocked origin');}
  catch(e){assert.ok(e instanceof IgnitionError);recovery=e.recovery;}
  assert.ok(recovery);assert.ok(recovery.distanceM>request.ignitionRadiusM);
  const moved=simulateLandscape(f,{...request,experiment:{parentId:'test',windOffset:0,windFactor:1,windShiftMinutes:0,ignitionOffset:toLocal(recovery.position,f.center)}},'moved',()=>{},origin);
  assert.ok(moved.cells.features.length>0);
  for(const c of moved.cells.features)assert.equal(intersectsCell(localPolygons(c.geometry,f.center),0,0,59),false);
  f.landcover.features[0].properties={categoria:'Aigua'};
  assert.throws(()=>simulateLandscape(f,request,'water',()=>{},origin),(e:unknown)=>e instanceof IgnitionError&&!e.recovery);
});
test('weather rejects null radiation, bad units, duplicated valid hours and missing horizons',()=>{const f=fixture();const raw={hourly_units:{temperature_2m:'°C',relative_humidity_2m:'%',wind_speed_10m:'km/h',wind_direction_10m:'°',direct_normal_irradiance:'W/m²',diffuse_radiation:'W/m²',precipitation:'mm'},hourly:{time:f.weather.map(w=>w.time),temperature_2m:f.weather.map(w=>w.temperatureC),relative_humidity_2m:f.weather.map(w=>w.humidityPct),wind_speed_10m:f.weather.map(w=>w.windKmh),wind_direction_10m:f.weather.map(w=>w.windFromDegrees),direct_normal_irradiance:f.weather.map(w=>w.directNormalWm2),diffuse_radiation:f.weather.map(w=>w.diffuseWm2),precipitation:f.weather.map(w=>w.precipitationMm)}};assert.equal(parseSimulationWeather(raw,Date.parse(origin)).length,6);assert.throws(()=>parseSimulationWeather({...raw,hourly_units:{...raw.hourly_units,wind_speed_10m:'mph'}},Date.parse(origin)));assert.throws(()=>parseSimulationWeather({...raw,hourly:{...raw.hourly,direct_normal_irradiance:[null,1,1,1,1,1]}},Date.parse(origin)));assert.throws(()=>parseSimulationWeather({...raw,hourly:{...raw.hourly,time:raw.hourly.time.map(()=>origin)}},Date.parse(origin)));});
console.log(`${count} SAGE checks passed`);
