import assert from 'node:assert/strict';
import {DeepfireProvider,polygonCollection} from '../src/lib/providers/deepfire';
import {readDeepfireContext} from '../src/lib/providers/deepfire-context';
import {clearProviderCacheForTests} from '../src/lib/providers/http';
import {buildPreventionPlan} from '../src/lib/prevention-plan';
import {buildEvidence} from '../src/lib/sage/analysis';
import {zonesAt} from '../src/lib/providers/catalonia';
import type {Assessment} from '../src/lib/assessment';
const original=global.fetch,token=process.env.DEEPFIRE_TOKEN,id=process.env.DEEPFIRE_CLIENT_ID,secret=process.env.DEEPFIRE_CLIENT_SECRET;
const now=new Date().toISOString();
const ring=[[1,41],[2,41],[2,42],[1,42],[1,41]];
const feature=(id:string,time=now)=>({type:'Feature',id,properties:{cluster_id:'cluster-1',computed_at:time,observed_watermark:time},geometry:{type:'MultiPolygon',coordinates:[[ring]]}});
const fc=(features:unknown[],extra={})=>({type:'FeatureCollection',features,...extra});
const json=(v:unknown)=>new Response(JSON.stringify(v),{headers:{'Content-Type':'application/json'}});
async function main(){
 process.env.DEEPFIRE_TOKEN='test-only';
 let calls=0;
 global.fetch=async(url)=>{const u=new URL(String(url));assert.equal(u.origin,'https://api.deepfire.co');if(u.pathname.includes('static-heat-sources'))assert.equal(u.searchParams.has('filter'),false);return json(fc([feature('a'),feature('b',new Date(Date.now()-3600000).toISOString())]));};
 const provider=new DeepfireProvider();
 assert.equal((await provider.perimeters()).data.features.length,1,'Latest perimeter per cluster');
 assert.equal((await provider.staticHeatSources()).data.features.length,2,'Static mask uses no active filter');
 assert.throws(()=>polygonCollection(fc([{...feature('x'),geometry:{type:'Polygon',coordinates:[[[1,41],[2,41],[2,42],[3,42]]]}}])),/geometry/);
 clearProviderCacheForTests();
 global.fetch=async(url)=>{const u=new URL(String(url));calls++;if(calls===1)return json(fc([feature('a')],{links:[{rel:'next',href:'https://evil.invalid/'}]}));assert.equal(u.searchParams.get('startIndex'),'1');return json(fc([feature('b')]));};
 await provider.staticHeatSources();assert.equal(calls,2);
 clearProviderCacheForTests();
 global.fetch=async(url)=>String(url).includes('clusters')?new Response('',{status:403}):json(fc([feature('a')]));
 const context=await readDeepfireContext([1,41,2,42]);assert.equal(context.sources[0].status,'unavailable');assert.equal(context.sources[1].status,'live');assert.equal(context.perimeters.features.length,1);
 delete process.env.DEEPFIRE_TOKEN;delete process.env.DEEPFIRE_CLIENT_ID;delete process.env.DEEPFIRE_CLIENT_SECRET;
 global.fetch=async()=>{throw Error('Must not call provider without credentials');};
 const disconnected=await readDeepfireContext([1,41,2,42]);assert.equal(disconnected.configured,false);assert.ok(disconnected.sources.every(s=>s.status==='unavailable'));
 const empty={type:'FeatureCollection' as const,features:[]};
 const assessment={generatedAt:now,location:{lat:41.5,lon:1.5,radiusM:1500},sources:[],weather:{outlook:[]},satellite:{hotspots:[]},geography:{buildings:empty,assets:empty,roads:empty},completeness:{missing:[]},forecast:{reason:'Missing inputs'},deepfire:disconnected} as unknown as Assessment;
 const plan=buildPreventionPlan(assessment);assert.ok(plan.some(p=>p.id==='restore-evidence'));assert.equal(new Set(plan.map(p=>p.category)).size,3);assert.ok(plan.every(p=>p.checks.length===3));assert.doesNotMatch(plan.find(p=>p.id==='asset-inspection')!.reason,/0 mapped/);
 assert.equal(buildEvidence(assessment).deepfire?.sources.length,3);
 const polygon=feature('z');polygon.properties={...polygon.properties,name:'Zone'} as typeof polygon.properties;
 assert.equal(zonesAt(fc([polygon]) as never,41.5,1.5).length,1);assert.equal(zonesAt(fc([polygon]) as never,40,1).length,0);
 console.log('PASS Deepfire polygons, latest snapshot, paging, partial failure, missing credentials, planning categories and AI evidence');
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>{global.fetch=original;for(const [k,v] of Object.entries({DEEPFIRE_TOKEN:token,DEEPFIRE_CLIENT_ID:id,DEEPFIRE_CLIENT_SECRET:secret})){if(v===undefined)delete process.env[k];else process.env[k]=v;}});
