import assert from 'node:assert/strict';
import {estimateVegetationDryness,drynessLevel,extremeDrynessHours} from '../src/lib/vegetation-dryness';
import {hourlyFFMC} from '../src/lib/receptivity/model';
import {parseWeather,type Assessment,type WeatherHour} from '../src/lib/assessment';
import {deriveIntelligence} from '../src/lib/intelligence';
import {buildPreventionPlan} from '../src/lib/prevention-plan';
import {buildEvidence} from '../src/lib/sage/analysis';
const now=Date.parse('2026-09-19T12:15Z'),start=Math.floor(now/3600000)*3600000;
function hour(offset:number,overrides:Partial<WeatherHour>={}):WeatherHour{return {time:new Date(start+offset*3600000).toISOString(),temperatureC:40,humidityPct:8,windKmh:20,windFromDegrees:180,precipitationMm:0,...overrides};}
function inputs(overrides:Partial<WeatherHour>={}){return {history:Array.from({length:72},(_,i)=>hour(i-71,overrides)),outlook:Array.from({length:24},(_,i)=>hour(i,overrides))};}
function estimate(overrides:Partial<WeatherHour>={}){const i=inputs(overrides);return estimateVegetationDryness(i.history,i.outlook,now);}
let count=0;function test(name:string,fn:()=>void){fn();count++;console.log('PASS',name);}
test('persistent hot dry weather produces an extreme estimate, never measured live moisture',()=>{const d=estimate();assert.equal(d.status,'estimated');assert.equal(d.current?.level,'extremely_dry');assert.ok(d.current!.moisturePct<6);assert.equal(d.liveFuelMoisturePct,null);assert.equal(d.outlook.length,24);assert.equal(d.historyHours,72);assert.ok(d.initializationSpreadPct!<2);});
test('persistent rain and humid weather produce a wetter estimate',()=>{const d=estimate({temperatureC:16,humidityPct:95,precipitationMm:1});assert.equal(d.status,'estimated');assert.equal(d.current?.level,'moist');assert.ok(d.current!.moisturePct>estimate().current!.moisturePct);assert.equal(extremeDrynessHours(d).length,0);});
test('rain in the forecast wets fuel without changing the current estimate',()=>{const i=inputs(),before=estimate();i.outlook[1].precipitationMm=12;const d=estimateVegetationDryness(i.history,i.outlook,now);assert.deepEqual(d.current,before.current);assert.ok(d.outlook[1].moisturePct>d.current!.moisturePct);});
test('current-hour rainfall is applied once, not twice',()=>{const i=inputs();i.history[71].precipitationMm=5;i.outlook[0].precipitationMm=5;let expected=85;for(const h of i.history)expected=hourlyFFMC(expected,{temperature:h.temperatureC,relativeHumidity:h.humidityPct,windSpeed:h.windKmh,precipitation:h.precipitationMm,stepHours:1});const d=estimateVegetationDryness(i.history,i.outlook,now);assert.equal(d.current?.ffmc,Number(expected.toFixed(2)));});
test('missing, duplicate, invalid and non-contiguous history cannot imply dryness',()=>{for(const mutate of [(i:ReturnType<typeof inputs>)=>i.history.splice(30,1),(i:ReturnType<typeof inputs>)=>i.history[30].time=i.history[29].time,(i:ReturnType<typeof inputs>)=>i.history[30].humidityPct=NaN,(i:ReturnType<typeof inputs>)=>i.history[30].precipitationMm=-1]){const i=inputs();mutate(i);const d=estimateVegetationDryness(i.history,i.outlook,now);assert.equal(d.status,'unavailable');assert.equal(d.current,null);assert.equal(extremeDrynessHours(d).length,0);}});
test('stale, future and incomplete outlooks do not return a current estimate',()=>{const i=inputs();for(const delta of [-3600000,3600000,86400000])assert.equal(estimateVegetationDryness(i.history,i.outlook,now+delta).status,'unavailable');i.outlook.pop();assert.equal(estimateVegetationDryness(i.history,i.outlook,now).status,'unavailable');});
test('history/outlook disagreement is withheld',()=>{const i=inputs();i.outlook[0].precipitationMm=5;assert.equal(estimateVegetationDryness(i.history,i.outlook,now).status,'unavailable');});
test('display bands have explicit exclusive boundaries',()=>{assert.equal(drynessLevel(5.99),'extremely_dry');assert.equal(drynessLevel(6),'very_dry');assert.equal(drynessLevel(10),'dry');assert.equal(drynessLevel(16),'moist');});
test('weather parser retains validated history for the integrated estimate',()=>{const {history,outlook}=inputs();const all=[...history,...outlook.slice(1)];const raw={hourly_units:{temperature_2m:'°C',relative_humidity_2m:'%',wind_speed_10m:'km/h',wind_direction_10m:'°',precipitation:'mm'},hourly:{time:all.map(h=>h.time.slice(0,16)),temperature_2m:all.map(h=>h.temperatureC),relative_humidity_2m:all.map(h=>h.humidityPct),wind_speed_10m:all.map(h=>h.windKmh),wind_direction_10m:all.map(h=>h.windFromDegrees),precipitation:all.map(h=>h.precipitationMm)}};const w=parseWeather(raw,now);assert.equal(w.history?.length,72);assert.equal(estimateVegetationDryness(w.history,w.outlook,now).current?.level,'extremely_dry');});
function assessment():Assessment{const i=inputs(),empty={type:'FeatureCollection' as const,features:[]};return {generatedAt:new Date(now).toISOString(),location:{lat:41.73,lon:1.83,radiusM:1500},sources:['Open-Meteo','OpenStreetMap / Overpass','NASA FIRMS'].map(source=>({source,status:'live',retrievedAt:new Date(now).toISOString(),detail:'Test fixture'})),weather:{...i,current:i.outlook[0],past72hPrecipitationMm:0,elevationM:300},vegetationDryness:estimate(),geography:{buildings:empty,roads:empty,landcover:empty,assets:empty},satellite:{hotspots:[],frpTrend:[],escalation:null},sage:{state:'review',reasons:[],ruleVersion:'test'},completeness:{available:[],missing:['Dead/live fuel moisture']},forecast:{available:false,reason:'Missing validated inputs'},units:{temperature:'°C',wind:'km/h',direction:'degrees',precipitation:'mm',elevation:'m',frp:'MW'}};}
test('extreme dryness reaches briefing, prevention checks and AI evidence without thermal escalation',()=>{const a=assessment(),r=deriveIntelligence(a);assert.equal(r.priority,'review');assert.match(r.headline,/Extremely dry/);assert.ok(r.actions.some(x=>x.id==='inspect-dry-fuels'));assert.ok(buildPreventionPlan(a).some(x=>x.id==='inspect-dry-fuels'));assert.equal(buildEvidence(a).vegetationDryness?.current?.level,'extremely_dry');assert.deepEqual(a.completeness.missing,['Dead/live fuel moisture']);});
test('stale weather and stale estimates cannot create dry-fuel inspection triggers',()=>{for(const kind of ['source','estimate','time']){const a=assessment();if(kind==='source')a.sources[0].status='stale';else if(kind==='estimate')a.vegetationDryness!.status='stale';else a.vegetationDryness!.current!.time=new Date(start-3600000).toISOString();assert.ok(!deriveIntelligence(a).actions.some(x=>x.id==='inspect-dry-fuels'));}});
console.log(`${count} vegetation dryness checks passed`);
