import assert from 'node:assert/strict';
import {preventionOpportunity,assessmentOpportunity} from '../src/lib/prevention-opportunity';
import {buildPreventionPlan} from '../src/lib/prevention-plan';
import type {MonitorZone} from '../src/lib/monitor';
import type {Assessment} from '../src/lib/assessment';

const now=Date.now(),stamp=new Date(now).toISOString();
const zone:MonitorZone={id:'test',name:'Test area',position:[1.83,41.73],state:'review',temperature:30,humidity:20,windKmh:30,hotspots:0,reasons:[],updatedAt:stamp,evidence:{weatherValidAt:stamp,weatherRetrievedAt:stamp,satelliteRetrievedAt:stamp,newestDetectionAt:null,weatherAgeMinutes:0,satelliteAgeMinutes:0,coverage:'test'},hazardWindow:{startsAt:new Date(now+8*3600000).toISOString(),endsAt:new Date(now+9*3600000).toISOString()},exposure:{status:'ready',sourceDate:stamp,importedAt:stamp,radiusM:15000,bufferM:0,total:2,counts:{school:1,road:1,healthcare:0,complex:0,gathering:0},score:10,uplift:10,hazardActive:true,contributions:[],nearby:[],detail:'Test inventory'}};
const full=preventionOpportunity(zone,now);
assert.equal(full.score,100);
assert.deepEqual(full.interventions.map(i=>i.id),['zone-monitoring','asset-inspection','patrol-attention']);
assert.equal(preventionOpportunity({...zone,exposure:undefined},now).score,null);
assert.equal(preventionOpportunity({...zone,exposure:{...zone.exposure!,status:'partial'}},now).score,null);
assert.equal(preventionOpportunity({...zone,updatedAt:new Date(now-3600000).toISOString()},now).score,null);
assert.equal(preventionOpportunity({...zone,evidence:{...zone.evidence!,satelliteRetrievedAt:new Date(now+60000).toISOString()}},now).score,null);
assert.equal(preventionOpportunity({...zone,windKmh:NaN},now).score,null);
const thermal=preventionOpportunity({...zone,hotspots:1},now);
assert.equal(thermal.score,null);assert.equal(thermal.status,'verify');
assert.ok(!thermal.interventions.some(i=>i.id==='patrol-attention'));
const unknown=preventionOpportunity({...zone,hotspots:null,temperature:null,evidence:undefined,exposure:undefined},now);
assert.equal(unknown.score,null);assert.equal(unknown.status,'unavailable');
assert.equal(preventionOpportunity({...zone,hazardWindow:null},now).score,70);
const immediate={...zone,hazardWindow:{startsAt:stamp,endsAt:new Date(now+3600000).toISOString()}};
assert.equal(preventionOpportunity(immediate,now).score,70);
assert.equal(preventionOpportunity({...zone,exposure:{...zone.exposure!,counts:{school:0,road:0,healthcare:0,complex:0,gathering:0}}},now).score,60);
assert.equal(preventionOpportunity({...zone,exposure:{...zone.exposure!,counts:{school:100,road:100,healthcare:0,complex:0,gathering:0}}},now).score,100,'Feature count cannot inflate opportunity');
assert.equal(preventionOpportunity({...zone,state:'escalating',exposure:{...zone.exposure!,uplift:40}},now).score,100,'Hazard priority and exposure uplift do not multiply preventability');
const empty={type:'FeatureCollection' as const,features:[]};
const a:Assessment={location:{lat:41.73,lon:1.83,radiusM:1500},generatedAt:stamp,sources:['Open-Meteo','Satellite detections','OpenStreetMap'].map(source=>({source,status:'live',retrievedAt:stamp,detail:'Fixture'})),weather:{current:{time:stamp,temperatureC:30,humidityPct:20,windKmh:30,windFromDegrees:180,precipitationMm:0},outlook:[{time:zone.hazardWindow!.startsAt,temperatureC:30,humidityPct:20,windKmh:30,windFromDegrees:180,precipitationMm:0}],past72hPrecipitationMm:null,elevationM:null},geography:{buildings:empty,landcover:empty,roads:empty,assets:empty},satellite:{hotspots:[],frpTrend:[],escalation:null},sage:{state:'review',reasons:[],ruleVersion:'test'},completeness:{available:[],missing:[]},forecast:{available:false,reason:'test'},units:{temperature:'C',wind:'km/h',direction:'degrees',precipitation:'mm',elevation:'m',frp:'MW'},exposure:zone.exposure};
assert.equal(assessmentOpportunity(a,now).score,100);
const plan=buildPreventionPlan(a);
for(const id of ['zone-monitoring','patrol-attention','asset-inspection'])assert.equal(plan.filter(p=>p.id===id).length,1);
assert.equal(plan.find(p=>p.id==='patrol-attention')?.checks.length,3);
console.log('PASS opportunity scoring, lead time, stale/missing/future evidence, thermal verification, feature-count caps, assessment parity and task proposals');
