const fs=require('node:fs');
const ts=require('typescript');
require.extensions['.ts']=(mod,filename)=>mod._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,filename);
const assert=require('node:assert/strict');
const {buildScenario,polygonAreaHa,pointInPolygon,estimateEvacuation,riskAt,CENTER}=require('../src/lib/simulation.ts');
let tests=0;function test(name,run){run();tests++;console.log('PASS',name);}
test('scenario reset is deterministic',()=>assert.deepEqual(buildScenario(0),buildScenario(0)));
test('detection, satellite, forecast milestones',()=>{assert.equal(buildScenario(0).incidentActive,false);assert.equal(buildScenario(10).incidentActive,true);assert.equal(buildScenario(19).satelliteConfirmed,false);assert.equal(buildScenario(20).satelliteConfirmed,true);assert.equal(buildScenario(30).forecastReady,true);});
test('exact first impact forecast',()=>assert.deepEqual(buildScenario(30).assets.slice(0,3).map(a=>a.eta),[31,48,61]));
test('evacuation margin drops 21 to 6 after update',()=>{assert.equal(buildScenario(30).assets[2].margin,21);assert.equal(buildScenario(45).assets[2].margin,6);});
test('new hotspots outside previous envelope',()=>assert.ok(buildScenario(42).deviation.outsideCount>0));
test('forecast envelope areas increase with horizon',()=>{let area=0;for(const horizon of [0,30,60,120,240]){const next=polygonAreaHa(buildScenario(30,horizon).envelopes[0].geometry);assert.ok(next>area);area=next;}});
test('uncertainty envelopes are nested in area',()=>{const e=buildScenario(30).envelopes.map(e=>polygonAreaHa(e.geometry));assert.ok(e[0]>e[1]&&e[1]>e[2]);});
test('ignition inside current perimeter',()=>assert.ok(pointInPolygon(CENTER,buildScenario(30).perimeter)));
test('evacuation reflects exit capacity',()=>assert.ok(estimateEvacuation(640,22,1,4,1.2)>estimateEvacuation(640,22,2,4,1.2)));
test('closed exits cannot produce a positive safe margin',()=>assert.equal(estimateEvacuation(640,22,0,4,1.2),999));
test('risk contributors sum to the score',()=>{for(const p of [CENTER,[1.3,41.7],[2.5,42.2]]){const r=riskAt(...p);assert.equal(r.contributors.reduce((s,c)=>s+c.value,0),r.score);}});
test('briefing cites its calculated values',()=>{const s=buildScenario(45);assert.ok(s.briefing.summary.includes(`${s.assets[2].margin} minutes`));assert.ok(s.briefing.priority.includes(`${s.assets[2].evacuation} minutes`));assert.equal(s.briefing.evidence.length,4);});
const {parseHotspots}=require('../src/lib/providers/deepfire.ts');
test('Deepfire documented payload normalization',()=>{const r=parseHotspots({type:'FeatureCollection',features:[{type:'Feature',id:'hotspots.sample',geometry:{type:'Point',coordinates:[1.86,41.3]},properties:{observed_at:'2026-09-19T10:40:00Z',cluster_id:'cluster',confidence:'HIGH',fire_radiative_power:49,source:'MTG',active:true}}]});assert.equal(r[0].frpMw,49);assert.equal(r[0].provenance.mode,'live');});
test('Deepfire malformed data rejected',()=>assert.throws(()=>parseHotspots({type:'FeatureCollection',features:[{geometry:{type:'Polygon',coordinates:[]}}]})));
const {escalation,parseSatelliteObservations,DemoCameraProvider}=require('../src/lib/providers/adapters.ts');
test('MTG escalation uses chronology and FRP',()=>{const o=[10,20,30,40].map((m,i)=>({id:String(i),observedAt:`2026-09-19T10:${m}:00Z`,position:[1.86,41.3],frpMw:[4,8,21,49][i]}));const e=escalation(o.reverse());assert.equal(e.ratio,12.25);assert.equal(e.minutes,30);assert.equal(e.rapid,true);});
test('invalid MTG negative FRP rejected',()=>assert.throws(()=>parseSatelliteObservations([{id:'a',position:[1,2],observedAt:'2026-09-19T10:00:00Z',frpMw:-1}])));
const {parseFirmsCSV}=require('../src/lib/providers/firms.ts');
const firmsHeader='latitude,longitude,acq_date,acq_time,frp,confidence';
test('FIRMS parses UTC acquisition time and real FRP',()=>{const [h]=parseFirmsCSV(firmsHeader+'\n41.18,1.23,2026-09-19,302,11.51,high');assert.equal(h.provenance.observedAt,'2026-09-19T03:02:00Z');assert.deepEqual(h.position,[1.23,41.18]);assert.equal(h.frpMw,11.51);assert.equal(h.provenance.mode,'live');});
test('FIRMS IDs stay stable when file ordering changes',()=>{const a='41.18,1.23,2026-09-19,302,11.51,high',b='41.45,1.97,2026-09-19,122,0.66,nominal';assert.equal(parseFirmsCSV(firmsHeader+'\n'+a+'\n'+b)[0].id,parseFirmsCSV(firmsHeader+'\n'+b+'\n'+a)[1].id);});
test('FIRMS invalid schema and coordinates rejected',()=>{assert.throws(()=>parseFirmsCSV('html,error'));assert.throws(()=>parseFirmsCSV(firmsHeader+'\n,1.23,2026-09-19,302,11.51,high'));assert.throws(()=>parseFirmsCSV(firmsHeader+'\n41,1.23,2026-09-19,2500,11.51,high'));});
(async()=>{const cam=new DemoCameraProvider();const base={cameraId:'test',observedAt:'2026-09-19T10:00:00Z',ambientC:34,baselineC:50,hotspotC:61,previousHotspotC:61,minutesElapsed:5,smokeConfidence:0,solarHeatingExpectedC:27};const hot=await cam.inspect(base);test('solar heating alone does not imply fire',()=>assert.equal(hot.data.priority,'LOW'));console.log(`\n${tests} checks passed`);})().catch(e=>{console.error(e);process.exitCode=1});
