import assert from 'node:assert/strict';
import {computeForecastExposure,exposureAtMinute} from '../src/lib/sage/forecast-exposure';
import {ExposureIndex} from '../src/lib/exposure/model';
import type {ExposureDataset,ExposureFeature} from '../src/lib/exposure/types';
import {cellPolygon,toLonLat} from '../src/lib/sage/geometry';
import {simulateLandscape} from '../src/lib/sage/engine';
import {applyScenarioContext,validateScenarioForRun,weatherAt} from '../src/lib/sage/scenario-context';
import type {ScenarioContext} from '../src/lib/product-contracts';
import type {Landscape,RunRequest} from '../src/lib/sage/types';
const center:[number,number]=[1.83,41.73],origin='2026-09-19T12:00:00.000Z';
const request:RunRequest={lat:center[1],lon:center[0],horizonMinutes:60,ignitionRadiusM:25,deadMoisturePct:7,liveMoisturePct:90,windAdjustment:.35,mode:'scenario',confirmation:'',solarDrying:false};
function landscape():Landscape{return {center,size:20,cellM:25,elevations:Array(400).fill(100),buildings:{type:'FeatureCollection',features:[]},landcover:{type:'FeatureCollection',features:[{type:'Feature',geometry:cellPolygon(0,0,250,center),properties:{categoria:'Prats i herbassars'}}]},weather:Array.from({length:6},(_,i)=>({time:new Date(Date.parse(origin)+i*3600000).toISOString(),temperatureC:30,humidityPct:20,windKmh:30,windFromDegrees:270,directNormalWm2:null,diffuseWm2:null,precipitationMm:0})),sources:[],warnings:[]};}
const run=simulateLandscape(landscape(),request,'test',()=>{},origin);
const point=(id:string,name:string,x:number,category:ExposureFeature['properties']['category']='healthcare'):ExposureFeature=>({type:'Feature',geometry:{type:'Point',coordinates:toLonLat([x,0],center)},properties:{id,name,category,kind:category,source:'fixture',sourceUrl:'test',occupancy:null}});
const road=(id:string,name:string,y:number):ExposureFeature=>({...point(id,name,0,'road'),geometry:{type:'LineString',coordinates:[toLonLat([-300,y],center),toLonLat([300,y],center)]}});
const dataset:ExposureDataset={type:'FeatureCollection',features:[point('hospital','Hospital',100),road('way/1','B-20',0),road('way/2','B-20',30),road('way/3','road',50),point('duplicate','Hospital',100),{...point('hospital-area','Hospital',100),geometry:cellPolygon(100,0,5,center)}],metadata:{version:1,sourceDate:origin,importedAt:origin,source:'fixture',sourceUrl:'fixture',license:'fixture',skipped:0,coverage:{type:'MultiPolygon',coordinates:[cellPolygon(0,0,1000,center).coordinates]},counts:{school:0,healthcare:3,complex:0,road:3,gathering:0}}};
const exposure=computeForecastExposure(run,new ExposureIndex(dataset),Date.parse(origin));
assert.equal(exposure.status,'ready');
assert.equal(exposure.assets.features.filter(f=>f.properties.category==='healthcare').length,1,'named facility point+area deduplicated');
const end=exposureAtMinute(exposure,60);
assert.equal(end.roadSegments,3);assert.equal(end.namedRoads,1);assert.equal(end.unidentifiedRoadSegments,1);
assert.ok(exposure.assets.features.find(f=>f.properties.id==='way/1')?.properties.arrivalCentralMinutes===0,'crossing line reaches ignition even endpoints outside');
const hospital=exposure.assets.features.find(f=>f.properties.id==='hospital-area')!.properties;
assert.ok(hospital.arrivalCentralMinutes!==null);
assert.ok(exposureAtMinute(exposure,hospital.arrivalCentralMinutes!-.001).central.every(a=>a.id!=='hospital-area'));
assert.ok(exposureAtMinute(exposure,hospital.arrivalCentralMinutes!).central.some(a=>a.id==='hospital-area'));
assert.equal(exposure.assets.features.find(f=>f.properties.id==='way/1')!.properties.coverage,'partial');
const outside={...dataset,metadata:{...dataset.metadata,coverage:{type:'MultiPolygon' as const,coordinates:[cellPolygon(5000,5000,100,center).coordinates]}}};
assert.equal(exposureAtMinute(computeForecastExposure(run,new ExposureIndex(outside)),60).counts,null);
const hole={...dataset,features:[{...point('courtyard','Courtyard',0),geometry:{type:'Polygon' as const,coordinates:[cellPolygon(0,0,300,center).coordinates[0],cellPolygon(0,0,275,center).coordinates[0]]}}]};
assert.equal(computeForecastExposure(run,new ExposureIndex(hole),Date.parse(origin)).assets.features.length,0,'polygon hole excludes model domain');
const context:ScenarioContext={version:1,id:'scenario-test',name:'Test',createdAt:origin,basis:'hypothetical',center,ignitionAt:origin,assessment:null,incident:null,evidence:[],inputs:{weather:landscape().weather,deadMoisturePct:7,liveMoisturePct:null},assumptions:[],limitations:[]};
validateScenarioForRun(context,request);
assert.throws(()=>validateScenarioForRun({...context,inputs:{...context.inputs,weather:[landscape().weather[0]]}},request),/cover/);
assert.throws(()=>validateScenarioForRun(context,{...request,solarDrying:true}),/radiation/);
assert.throws(()=>validateScenarioForRun(context,{...request,lon:2}),/location/);
assert.equal(weatherAt([{...landscape().weather[0],validForMinutes:30}],Date.parse(origin)+30*60000),undefined);
const wetter=simulateLandscape(applyScenarioContext(landscape(),context,{...request,deadMoisturePct:20}),{...request,deadMoisturePct:20},'wet',()=>{},origin);
assert.ok(wetter.stats.burnedHa<run.stats.burnedHa,'transferred/overridden moisture reaches real spread calculation');
const westContext={...context,inputs:{...context.inputs,weather:context.inputs.weather.map(w=>({...w,windFromDegrees:90}))}};
const west=simulateLandscape(applyScenarioContext(landscape(),westContext,request),request,'west',()=>{},origin);
assert.notDeepEqual(west.cells,run.cells,'captured wind direction reaches spread calculation');
assert.throws(()=>simulateLandscape(landscape(),{...request,solarDrying:true},'bad',()=>{},origin),/radiation/);
const observed=simulateLandscape(landscape(),request,'incident',()=>{},origin,{initialObservation:{geometry:cellPolygon(100,0,5,center),observedAt:origin,source:'Operator surveyed perimeter'}});
assert.ok(observed.cells.features.some(f=>f.properties?.arrivalCentral===0&&f.geometry.coordinates[0][0][0]>center[0]),'incident polygon initializes actual mapped extent');
assert.ok(observed.assumptions.some(a=>a.includes('Operator surveyed perimeter')));
console.log('PASS forecast exposure: geometry, deduplication, road units, timeline, coverage, immutable forcing, moisture/wind integration, missing radiation');
