import {cached,isoNow} from './http';
import type {Hotspot,ProviderResult} from './types';
export const FIRMS_URL='https://firms.modaps.eosdis.nasa.gov/data/active_fire/noaa-20-viirs-c2/csv/J1_VIIRS_C2_Europe_24h.csv';
export function parseFirmsCSV(csv:string):Hotspot[]{
 const lines=csv.trim().split(/\r?\n/);const keys=lines.shift()!.split(',');
 for(const k of ['latitude','longitude','acq_date','acq_time','frp','confidence'])if(!keys.includes(k))throw Error('Invalid FIRMS CSV schema');
 return lines.filter(Boolean).map((line)=>{const v=line.split(',');const row=Object.fromEntries(keys.map((k,j)=>[k,v[j]]));const lat=Number(row.latitude),lon=Number(row.longitude),time=row.acq_time.padStart(4,'0');const observedAt=`${row.acq_date}T${time.slice(0,2)}:${time.slice(2)}:00Z`;if(!row.latitude?.trim()||!row.longitude?.trim()||!/^\d{4}$/.test(time)||Number(time.slice(0,2))>23||Number(time.slice(2))>59||!Number.isFinite(lat)||Math.abs(lat)>90||!Number.isFinite(lon)||Math.abs(lon)>180||!Number.isFinite(Date.parse(observedAt)))throw Error('Invalid FIRMS observation');return{raw:row,id:`N20-${row.acq_date}-${time}-${lat}-${lon}`,position:[lon,lat] as [number,number],clusterId:null,frpMw:row.frp!==''&&Number.isFinite(Number(row.frp))?Number(row.frp):null,confidence:row.confidence,provenance:{source:'NASA FIRMS · NOAA-20 VIIRS 375m',observedAt,retrievedAt:isoNow(),mode:'live' as const}};});
}
export async function firmsHotspots():Promise<ProviderResult<Hotspot[]>>{return cached('firms-europe-24h',600_000,async()=>{const r=await fetch(FIRMS_URL,{signal:AbortSignal.timeout(15000),cache:'no-store'});if(!r.ok)throw Error(`FIRMS HTTP ${r.status}`);const data=parseFirmsCSV(await r.text());const newest=Math.max(...data.map(h=>Date.parse(h.provenance.observedAt)));return {data,status:Date.now()-newest>36*3600_000?'stale':'live',updatedAt:isoNow(),detail:`${data.length} Europe detections from the public 24-hour file. Satellite thermal anomalies, not confirmed wildfire incidents.`};});}
